In [6]:
import torch
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(1)

pGT = torch.Tensor([1./12, 2./12, 3./12, 3./12, 2./12, 1./12])
y = torch.from_numpy(np.random.choice(list(range(6)), size=1000, p=pGT.numpy())).type(torch.int64).view(-1, 1)
delta = torch.zeros(y.numel(),6).scatter(1,y,torch.ones_like(y).float())

In [3]:
print(y.size())
print(delta.size())

torch.Size([1000, 1])
torch.Size([1000, 6])


In [8]:
def MaxLik(delta):
    alpha = 1
    theta = torch.randn(6)
    for iter in range(100):
        p_theta = torch.nn.Softmax(dim=0)(theta)
        g = torch.mean(p_theta-delta,0)
        theta = theta - alpha*g
        print("Diff: %f" % torch.norm(p_theta - pGT))
    
    return theta

theta = MaxLik(delta)
theta

Diff: 0.325280
Diff: 0.253495
Diff: 0.202513
Diff: 0.164393
Diff: 0.134917
Diff: 0.111672
Diff: 0.093129
Diff: 0.078231
Diff: 0.066204
Diff: 0.056461
Diff: 0.048543
Diff: 0.042092
Diff: 0.036826
Diff: 0.032520
Diff: 0.028997
Diff: 0.026114
Diff: 0.023757
Diff: 0.021835
Diff: 0.020272
Diff: 0.019006
Diff: 0.017986
Diff: 0.017170
Diff: 0.016519
Diff: 0.016005
Diff: 0.015602
Diff: 0.015288
Diff: 0.015046
Diff: 0.014862
Diff: 0.014724
Diff: 0.014622
Diff: 0.014549
Diff: 0.014499
Diff: 0.014466
Diff: 0.014447
Diff: 0.014438
Diff: 0.014437
Diff: 0.014442
Diff: 0.014451
Diff: 0.014464
Diff: 0.014478
Diff: 0.014495
Diff: 0.014512
Diff: 0.014529
Diff: 0.014547
Diff: 0.014565
Diff: 0.014582
Diff: 0.014598
Diff: 0.014614
Diff: 0.014629
Diff: 0.014644
Diff: 0.014658
Diff: 0.014671
Diff: 0.014683
Diff: 0.014695
Diff: 0.014706
Diff: 0.014716
Diff: 0.014726
Diff: 0.014735
Diff: 0.014743
Diff: 0.014751
Diff: 0.014758
Diff: 0.014765
Diff: 0.014771
Diff: 0.014777
Diff: 0.014782
Diff: 0.014787
Diff: 0.01

tensor([-0.4159,  0.1532,  0.5856,  0.6138,  0.2491, -0.5461])

In [7]:

#maximum likelihood given dataset y encoded in delta


#reinforce with reward R
def Reinforce(R, theta=None):
    alpha = 1
    if theta is None:
        theta = torch.randn(6)
    for iter in range(10000):
        #current distribution
        p_theta = torch.nn.Softmax(dim=0)(theta)

        #sample from current distribution and compute reward
        ##############################
        ## Sample from p_theta, find the assignment delta and compute the reward
        ## for each sample
        ## Dimensions: cPT (6); y (1000x1 -> 1000x1); delta (1000x6); curReward (1000x1)
        ############################## 
        y = torch.from_numpy(np.random.choice(list(range(6)), size=1000, p=p_theta.numpy())).type(torch.int64).view(-1, 1)
        delta = torch.zeros(y.numel(),6).scatter(1,y,torch.ones_like(y).float())
        curReward = pGT

        #compute gradient and update
        g = torch.mean(curReward*(delta - p_theta),0)
        theta = theta + alpha*g
        print("Diff: %f" % torch.norm(p_theta - pGT))
        print(p_theta)

R = pGT
Reinforce(R, theta)
    


Diff: 0.014845
tensor([0.0900, 0.1590, 0.2450, 0.2520, 0.1750, 0.0790])
Diff: 0.015538
tensor([0.0901, 0.1589, 0.2442, 0.2521, 0.1756, 0.0792])
Diff: 0.014862
tensor([0.0900, 0.1590, 0.2448, 0.2525, 0.1748, 0.0790])
Diff: 0.015491
tensor([0.0899, 0.1591, 0.2438, 0.2531, 0.1752, 0.0790])
Diff: 0.015071
tensor([0.0899, 0.1590, 0.2446, 0.2526, 0.1751, 0.0789])
Diff: 0.016564
tensor([0.0898, 0.1588, 0.2426, 0.2546, 0.1753, 0.0789])
Diff: 0.016871
tensor([0.0900, 0.1592, 0.2418, 0.2555, 0.1748, 0.0788])
Diff: 0.016690
tensor([0.0898, 0.1597, 0.2415, 0.2558, 0.1744, 0.0787])
Diff: 0.016527
tensor([0.0900, 0.1601, 0.2412, 0.2557, 0.1741, 0.0788])
Diff: 0.016840
tensor([0.0899, 0.1599, 0.2412, 0.2561, 0.1742, 0.0787])
Diff: 0.017760
tensor([0.0898, 0.1587, 0.2413, 0.2576, 0.1740, 0.0786])
Diff: 0.018500
tensor([0.0901, 0.1586, 0.2404, 0.2574, 0.1747, 0.0787])
Diff: 0.018325
tensor([0.0902, 0.1587, 0.2405, 0.2565, 0.1752, 0.0789])
Diff: 0.018479
tensor([0.0902, 0.1581, 0.2410, 0.2566, 0.1753, 0

Diff: 0.031515
tensor([0.0923, 0.1620, 0.2255, 0.2610, 0.1792, 0.0800])
Diff: 0.032024
tensor([0.0922, 0.1613, 0.2254, 0.2617, 0.1795, 0.0798])
Diff: 0.032283
tensor([0.0922, 0.1615, 0.2250, 0.2621, 0.1791, 0.0800])
Diff: 0.032937
tensor([0.0923, 0.1618, 0.2244, 0.2632, 0.1785, 0.0798])
Diff: 0.033702
tensor([0.0923, 0.1614, 0.2240, 0.2638, 0.1788, 0.0798])
Diff: 0.033048
tensor([0.0924, 0.1620, 0.2242, 0.2626, 0.1789, 0.0799])
Diff: 0.033228
tensor([0.0924, 0.1625, 0.2238, 0.2625, 0.1789, 0.0799])
Diff: 0.033176
tensor([0.0923, 0.1623, 0.2240, 0.2625, 0.1791, 0.0798])
Diff: 0.032908
tensor([0.0922, 0.1622, 0.2243, 0.2634, 0.1782, 0.0798])
Diff: 0.032572
tensor([0.0922, 0.1618, 0.2247, 0.2630, 0.1784, 0.0799])
Diff: 0.031902
tensor([0.0924, 0.1623, 0.2250, 0.2620, 0.1783, 0.0801])
Diff: 0.033214
tensor([0.0924, 0.1621, 0.2239, 0.2632, 0.1783, 0.0801])
Diff: 0.034685
tensor([0.0925, 0.1617, 0.2228, 0.2642, 0.1787, 0.0802])
Diff: 0.035399
tensor([0.0924, 0.1612, 0.2225, 0.2652, 0.1787, 0

tensor([0.0932, 0.1650, 0.2123, 0.2685, 0.1818, 0.0792])
Diff: 0.046329
tensor([0.0933, 0.1647, 0.2120, 0.2680, 0.1828, 0.0792])
Diff: 0.046530
tensor([0.0931, 0.1648, 0.2120, 0.2689, 0.1823, 0.0790])
Diff: 0.046162
tensor([0.0931, 0.1650, 0.2123, 0.2690, 0.1818, 0.0789])
Diff: 0.044325
tensor([0.0932, 0.1651, 0.2136, 0.2673, 0.1817, 0.0790])
Diff: 0.044829
tensor([0.0930, 0.1651, 0.2133, 0.2684, 0.1812, 0.0790])
Diff: 0.045145
tensor([0.0929, 0.1651, 0.2131, 0.2688, 0.1811, 0.0789])
Diff: 0.044323
tensor([0.0929, 0.1656, 0.2136, 0.2682, 0.1807, 0.0789])
Diff: 0.043924
tensor([0.0931, 0.1660, 0.2138, 0.2673, 0.1809, 0.0789])
Diff: 0.042535
tensor([0.0932, 0.1658, 0.2150, 0.2662, 0.1808, 0.0789])
Diff: 0.043017
tensor([0.0931, 0.1655, 0.2147, 0.2669, 0.1809, 0.0788])
Diff: 0.041761
tensor([0.0935, 0.1661, 0.2155, 0.2652, 0.1807, 0.0790])
Diff: 0.041185
tensor([0.0933, 0.1652, 0.2163, 0.2658, 0.1806, 0.0788])
Diff: 0.041339
tensor([0.0934, 0.1661, 0.2158, 0.2648, 0.1809, 0.0790])
Diff: 0

Diff: 0.042598
tensor([0.0910, 0.1616, 0.2184, 0.2745, 0.1767, 0.0778])
Diff: 0.041768
tensor([0.0911, 0.1618, 0.2190, 0.2739, 0.1765, 0.0778])
Diff: 0.041569
tensor([0.0911, 0.1616, 0.2193, 0.2742, 0.1761, 0.0778])
Diff: 0.040915
tensor([0.0909, 0.1620, 0.2197, 0.2737, 0.1759, 0.0778])
Diff: 0.041471
tensor([0.0907, 0.1621, 0.2194, 0.2743, 0.1758, 0.0776])
Diff: 0.042992
tensor([0.0905, 0.1623, 0.2185, 0.2760, 0.1752, 0.0776])
Diff: 0.043503
tensor([0.0904, 0.1623, 0.2180, 0.2762, 0.1756, 0.0775])
Diff: 0.044588
tensor([0.0905, 0.1617, 0.2174, 0.2772, 0.1756, 0.0775])
Diff: 0.046095
tensor([0.0905, 0.1616, 0.2164, 0.2785, 0.1754, 0.0776])
Diff: 0.044439
tensor([0.0907, 0.1614, 0.2175, 0.2768, 0.1759, 0.0777])
Diff: 0.044749
tensor([0.0908, 0.1618, 0.2169, 0.2765, 0.1762, 0.0778])
Diff: 0.044870
tensor([0.0909, 0.1626, 0.2165, 0.2767, 0.1755, 0.0778])
Diff: 0.046389
tensor([0.0908, 0.1620, 0.2161, 0.2788, 0.1747, 0.0777])
Diff: 0.047287
tensor([0.0906, 0.1622, 0.2155, 0.2796, 0.1745, 0

tensor([0.0890, 0.1608, 0.2271, 0.2806, 0.1660, 0.0765])
Diff: 0.039436
tensor([0.0891, 0.1603, 0.2277, 0.2806, 0.1658, 0.0765])
Diff: 0.038691
tensor([0.0889, 0.1602, 0.2284, 0.2802, 0.1657, 0.0765])
Diff: 0.039494
tensor([0.0892, 0.1599, 0.2275, 0.2805, 0.1662, 0.0767])
Diff: 0.038802
tensor([0.0893, 0.1600, 0.2278, 0.2798, 0.1663, 0.0769])
Diff: 0.039561
tensor([0.0892, 0.1605, 0.2271, 0.2804, 0.1661, 0.0767])
Diff: 0.040647
tensor([0.0891, 0.1598, 0.2270, 0.2816, 0.1659, 0.0766])
Diff: 0.041050
tensor([0.0892, 0.1601, 0.2265, 0.2818, 0.1658, 0.0766])
Diff: 0.040922
tensor([0.0891, 0.1595, 0.2271, 0.2819, 0.1658, 0.0765])
Diff: 0.040308
tensor([0.0891, 0.1600, 0.2273, 0.2814, 0.1655, 0.0767])
Diff: 0.039406
tensor([0.0891, 0.1599, 0.2281, 0.2808, 0.1656, 0.0765])
Diff: 0.039178
tensor([0.0891, 0.1599, 0.2282, 0.2805, 0.1658, 0.0765])
Diff: 0.039475
tensor([0.0891, 0.1599, 0.2279, 0.2807, 0.1659, 0.0765])
Diff: 0.040862
tensor([0.0891, 0.1597, 0.2271, 0.2819, 0.1657, 0.0765])
Diff: 0

Diff: 0.052017
tensor([0.0887, 0.1633, 0.2173, 0.2894, 0.1636, 0.0776])
Diff: 0.051880
tensor([0.0886, 0.1630, 0.2174, 0.2893, 0.1641, 0.0775])
Diff: 0.053200
tensor([0.0886, 0.1631, 0.2164, 0.2903, 0.1641, 0.0776])
Diff: 0.053749
tensor([0.0884, 0.1628, 0.2160, 0.2907, 0.1643, 0.0777])
Diff: 0.054156
tensor([0.0885, 0.1631, 0.2154, 0.2907, 0.1644, 0.0778])
Diff: 0.054214
tensor([0.0884, 0.1637, 0.2149, 0.2904, 0.1648, 0.0778])
Diff: 0.052823
tensor([0.0886, 0.1637, 0.2156, 0.2892, 0.1651, 0.0778])
Diff: 0.052179
tensor([0.0886, 0.1634, 0.2163, 0.2889, 0.1651, 0.0778])
Diff: 0.052412
tensor([0.0887, 0.1637, 0.2157, 0.2887, 0.1654, 0.0778])
Diff: 0.052133
tensor([0.0885, 0.1636, 0.2163, 0.2889, 0.1651, 0.0777])
Diff: 0.052219
tensor([0.0885, 0.1640, 0.2161, 0.2889, 0.1649, 0.0776])
Diff: 0.052960
tensor([0.0885, 0.1642, 0.2154, 0.2893, 0.1651, 0.0775])
Diff: 0.052733
tensor([0.0885, 0.1632, 0.2160, 0.2894, 0.1654, 0.0774])
Diff: 0.052824
tensor([0.0884, 0.1635, 0.2158, 0.2893, 0.1655, 0

tensor([0.0886, 0.1634, 0.2186, 0.2919, 0.1602, 0.0773])
Diff: 0.055518
tensor([0.0884, 0.1633, 0.2179, 0.2938, 0.1595, 0.0771])
Diff: 0.054436
tensor([0.0884, 0.1631, 0.2183, 0.2929, 0.1601, 0.0772])
Diff: 0.055925
tensor([0.0882, 0.1624, 0.2179, 0.2944, 0.1598, 0.0772])
Diff: 0.053860
tensor([0.0883, 0.1630, 0.2184, 0.2924, 0.1607, 0.0772])
Diff: 0.053952
tensor([0.0882, 0.1627, 0.2185, 0.2925, 0.1608, 0.0773])
Diff: 0.055299
tensor([0.0881, 0.1629, 0.2179, 0.2937, 0.1602, 0.0773])
Diff: 0.055340
tensor([0.0882, 0.1631, 0.2179, 0.2937, 0.1599, 0.0773])
Diff: 0.054516
tensor([0.0883, 0.1629, 0.2184, 0.2930, 0.1600, 0.0773])
Diff: 0.054256
tensor([0.0884, 0.1628, 0.2186, 0.2929, 0.1601, 0.0773])
Diff: 0.054841
tensor([0.0886, 0.1629, 0.2183, 0.2933, 0.1597, 0.0772])
Diff: 0.054959
tensor([0.0884, 0.1623, 0.2187, 0.2937, 0.1597, 0.0772])
Diff: 0.054541
tensor([0.0886, 0.1627, 0.2184, 0.2930, 0.1599, 0.0773])
Diff: 0.055367
tensor([0.0886, 0.1622, 0.2182, 0.2938, 0.1598, 0.0773])
Diff: 0

tensor([0.0868, 0.1585, 0.2202, 0.3003, 0.1584, 0.0759])
Diff: 0.058609
tensor([0.0869, 0.1586, 0.2207, 0.2988, 0.1591, 0.0759])
Diff: 0.058586
tensor([0.0867, 0.1592, 0.2208, 0.2989, 0.1587, 0.0758])
Diff: 0.059287
tensor([0.0867, 0.1586, 0.2209, 0.2996, 0.1583, 0.0758])
Diff: 0.060409
tensor([0.0867, 0.1583, 0.2203, 0.3006, 0.1583, 0.0758])
Diff: 0.060988
tensor([0.0868, 0.1582, 0.2200, 0.3011, 0.1580, 0.0759])
Diff: 0.060864
tensor([0.0868, 0.1580, 0.2202, 0.3010, 0.1581, 0.0759])
Diff: 0.060458
tensor([0.0868, 0.1579, 0.2208, 0.3008, 0.1579, 0.0759])
Diff: 0.060834
tensor([0.0870, 0.1574, 0.2201, 0.3009, 0.1586, 0.0760])
Diff: 0.061531
tensor([0.0870, 0.1573, 0.2198, 0.3015, 0.1585, 0.0759])
Diff: 0.061544
tensor([0.0872, 0.1575, 0.2197, 0.3014, 0.1583, 0.0759])
Diff: 0.062194
tensor([0.0871, 0.1571, 0.2196, 0.3021, 0.1582, 0.0759])
Diff: 0.062368
tensor([0.0870, 0.1566, 0.2200, 0.3024, 0.1581, 0.0759])
Diff: 0.062292
tensor([0.0870, 0.1571, 0.2198, 0.3023, 0.1580, 0.0758])
Diff: 0

tensor([0.0892, 0.1579, 0.2276, 0.2919, 0.1571, 0.0763])
Diff: 0.050491
tensor([0.0892, 0.1578, 0.2275, 0.2923, 0.1570, 0.0763])
Diff: 0.050692
tensor([0.0891, 0.1579, 0.2274, 0.2925, 0.1569, 0.0762])
Diff: 0.050144
tensor([0.0893, 0.1577, 0.2276, 0.2919, 0.1572, 0.0763])
Diff: 0.048562
tensor([0.0894, 0.1581, 0.2280, 0.2905, 0.1576, 0.0764])
Diff: 0.046403
tensor([0.0895, 0.1582, 0.2292, 0.2886, 0.1580, 0.0765])
Diff: 0.046245
tensor([0.0896, 0.1587, 0.2289, 0.2883, 0.1580, 0.0764])
Diff: 0.046081
tensor([0.0897, 0.1589, 0.2285, 0.2880, 0.1584, 0.0765])
Diff: 0.043240
tensor([0.0898, 0.1592, 0.2306, 0.2857, 0.1582, 0.0765])
Diff: 0.044188
tensor([0.0900, 0.1597, 0.2292, 0.2862, 0.1582, 0.0767])
Diff: 0.045036
tensor([0.0899, 0.1595, 0.2288, 0.2870, 0.1581, 0.0767])
Diff: 0.044086
tensor([0.0899, 0.1595, 0.2293, 0.2862, 0.1583, 0.0768])
Diff: 0.044191
tensor([0.0899, 0.1594, 0.2294, 0.2863, 0.1581, 0.0769])
Diff: 0.043708
tensor([0.0901, 0.1595, 0.2292, 0.2857, 0.1585, 0.0770])
Diff: 0

Diff: 0.063729
tensor([0.0918, 0.1657, 0.2075, 0.2961, 0.1604, 0.0786])
Diff: 0.064829
tensor([0.0917, 0.1660, 0.2066, 0.2968, 0.1604, 0.0785])
Diff: 0.065403
tensor([0.0917, 0.1654, 0.2067, 0.2976, 0.1602, 0.0785])
Diff: 0.066251
tensor([0.0918, 0.1658, 0.2059, 0.2980, 0.1601, 0.0784])
Diff: 0.065287
tensor([0.0920, 0.1656, 0.2066, 0.2973, 0.1601, 0.0785])
Diff: 0.065346
tensor([0.0921, 0.1666, 0.2060, 0.2968, 0.1601, 0.0785])
Diff: 0.064819
tensor([0.0921, 0.1670, 0.2062, 0.2962, 0.1599, 0.0786])
Diff: 0.064708
tensor([0.0921, 0.1670, 0.2063, 0.2962, 0.1599, 0.0785])
Diff: 0.065566
tensor([0.0921, 0.1673, 0.2051, 0.2963, 0.1604, 0.0787])
Diff: 0.065957
tensor([0.0920, 0.1667, 0.2049, 0.2968, 0.1609, 0.0786])
Diff: 0.065401
tensor([0.0920, 0.1664, 0.2058, 0.2968, 0.1605, 0.0785])
Diff: 0.065740
tensor([0.0919, 0.1662, 0.2055, 0.2970, 0.1608, 0.0785])
Diff: 0.067123
tensor([0.0919, 0.1659, 0.2048, 0.2983, 0.1607, 0.0785])
Diff: 0.065402
tensor([0.0921, 0.1666, 0.2050, 0.2961, 0.1616, 0

Diff: 0.051634
tensor([0.0937, 0.1719, 0.2118, 0.2820, 0.1601, 0.0806])
Diff: 0.051329
tensor([0.0935, 0.1720, 0.2121, 0.2819, 0.1601, 0.0804])
Diff: 0.050653
tensor([0.0934, 0.1713, 0.2137, 0.2825, 0.1588, 0.0803])
Diff: 0.051016
tensor([0.0935, 0.1721, 0.2131, 0.2822, 0.1587, 0.0803])
Diff: 0.049884
tensor([0.0937, 0.1729, 0.2135, 0.2807, 0.1588, 0.0804])
Diff: 0.050847
tensor([0.0935, 0.1724, 0.2131, 0.2819, 0.1587, 0.0803])
Diff: 0.050138
tensor([0.0933, 0.1723, 0.2138, 0.2816, 0.1587, 0.0802])
Diff: 0.048443
tensor([0.0934, 0.1720, 0.2150, 0.2804, 0.1590, 0.0802])
Diff: 0.048043
tensor([0.0934, 0.1715, 0.2154, 0.2803, 0.1591, 0.0802])
Diff: 0.048268
tensor([0.0935, 0.1720, 0.2151, 0.2801, 0.1590, 0.0802])
Diff: 0.048260
tensor([0.0938, 0.1723, 0.2149, 0.2798, 0.1590, 0.0804])
Diff: 0.048017
tensor([0.0937, 0.1722, 0.2154, 0.2799, 0.1585, 0.0802])
Diff: 0.048955
tensor([0.0937, 0.1726, 0.2144, 0.2803, 0.1587, 0.0803])
Diff: 0.049341
tensor([0.0936, 0.1725, 0.2144, 0.2808, 0.1585, 0

tensor([0.0937, 0.1770, 0.2102, 0.2729, 0.1653, 0.0808])
Diff: 0.048684
tensor([0.0936, 0.1770, 0.2101, 0.2736, 0.1651, 0.0807])
Diff: 0.049133
tensor([0.0938, 0.1773, 0.2095, 0.2734, 0.1651, 0.0809])
Diff: 0.049301
tensor([0.0937, 0.1774, 0.2093, 0.2732, 0.1655, 0.0809])
Diff: 0.050873
tensor([0.0937, 0.1775, 0.2080, 0.2743, 0.1657, 0.0808])
Diff: 0.052252
tensor([0.0937, 0.1782, 0.2069, 0.2749, 0.1656, 0.0807])
Diff: 0.052392
tensor([0.0937, 0.1784, 0.2064, 0.2744, 0.1663, 0.0808])
Diff: 0.053170
tensor([0.0935, 0.1781, 0.2060, 0.2755, 0.1663, 0.0807])
Diff: 0.053933
tensor([0.0937, 0.1778, 0.2052, 0.2757, 0.1668, 0.0808])
Diff: 0.054424
tensor([0.0938, 0.1779, 0.2046, 0.2756, 0.1672, 0.0809])
Diff: 0.053681
tensor([0.0938, 0.1777, 0.2053, 0.2754, 0.1669, 0.0809])
Diff: 0.053529
tensor([0.0939, 0.1779, 0.2050, 0.2744, 0.1678, 0.0810])
Diff: 0.053107
tensor([0.0941, 0.1775, 0.2055, 0.2744, 0.1674, 0.0811])
Diff: 0.052405
tensor([0.0942, 0.1772, 0.2059, 0.2737, 0.1677, 0.0813])
Diff: 0

Diff: 0.058544
tensor([0.0933, 0.1783, 0.2017, 0.2791, 0.1673, 0.0803])
Diff: 0.058678
tensor([0.0933, 0.1785, 0.2017, 0.2794, 0.1669, 0.0802])
Diff: 0.057367
tensor([0.0933, 0.1784, 0.2029, 0.2787, 0.1666, 0.0801])
Diff: 0.058435
tensor([0.0932, 0.1784, 0.2022, 0.2797, 0.1663, 0.0802])
Diff: 0.059160
tensor([0.0930, 0.1778, 0.2020, 0.2812, 0.1659, 0.0801])
Diff: 0.058981
tensor([0.0931, 0.1783, 0.2019, 0.2804, 0.1662, 0.0801])
Diff: 0.059713
tensor([0.0932, 0.1781, 0.2013, 0.2809, 0.1662, 0.0802])
Diff: 0.059912
tensor([0.0934, 0.1780, 0.2009, 0.2807, 0.1665, 0.0804])
Diff: 0.058998
tensor([0.0933, 0.1777, 0.2015, 0.2800, 0.1672, 0.0803])
Diff: 0.058457
tensor([0.0933, 0.1777, 0.2018, 0.2793, 0.1676, 0.0803])
Diff: 0.058670
tensor([0.0931, 0.1772, 0.2016, 0.2797, 0.1681, 0.0803])
Diff: 0.059422
tensor([0.0933, 0.1769, 0.2008, 0.2799, 0.1688, 0.0803])
Diff: 0.059306
tensor([0.0933, 0.1762, 0.2009, 0.2801, 0.1692, 0.0803])
Diff: 0.058561
tensor([0.0933, 0.1764, 0.2015, 0.2795, 0.1690, 0

Diff: 0.051654
tensor([0.0915, 0.1801, 0.2086, 0.2761, 0.1650, 0.0788])
Diff: 0.050781
tensor([0.0915, 0.1797, 0.2094, 0.2759, 0.1647, 0.0787])
Diff: 0.051016
tensor([0.0916, 0.1802, 0.2089, 0.2753, 0.1653, 0.0787])
Diff: 0.050611
tensor([0.0917, 0.1800, 0.2092, 0.2750, 0.1653, 0.0788])
Diff: 0.050017
tensor([0.0918, 0.1793, 0.2097, 0.2749, 0.1654, 0.0789])
Diff: 0.049642
tensor([0.0920, 0.1789, 0.2097, 0.2745, 0.1657, 0.0792])
Diff: 0.051247
tensor([0.0920, 0.1795, 0.2084, 0.2753, 0.1655, 0.0792])
Diff: 0.051379
tensor([0.0919, 0.1794, 0.2086, 0.2759, 0.1651, 0.0791])
Diff: 0.051429
tensor([0.0921, 0.1795, 0.2083, 0.2754, 0.1654, 0.0793])
Diff: 0.051096
tensor([0.0922, 0.1800, 0.2086, 0.2750, 0.1649, 0.0793])
Diff: 0.050998
tensor([0.0923, 0.1802, 0.2085, 0.2744, 0.1652, 0.0794])
Diff: 0.050399
tensor([0.0924, 0.1805, 0.2087, 0.2734, 0.1656, 0.0793])
Diff: 0.051396
tensor([0.0924, 0.1813, 0.2080, 0.2737, 0.1653, 0.0793])
Diff: 0.051117
tensor([0.0922, 0.1813, 0.2084, 0.2738, 0.1650, 0

Diff: 0.041460
tensor([0.0933, 0.1822, 0.2149, 0.2615, 0.1685, 0.0796])
Diff: 0.041248
tensor([0.0932, 0.1821, 0.2151, 0.2614, 0.1686, 0.0796])
Diff: 0.041934
tensor([0.0931, 0.1824, 0.2145, 0.2616, 0.1688, 0.0796])
Diff: 0.042289
tensor([0.0930, 0.1824, 0.2142, 0.2621, 0.1687, 0.0796])
Diff: 0.042919
tensor([0.0930, 0.1821, 0.2135, 0.2625, 0.1692, 0.0797])
Diff: 0.043089
tensor([0.0931, 0.1825, 0.2133, 0.2620, 0.1692, 0.0798])
Diff: 0.043824
tensor([0.0930, 0.1830, 0.2128, 0.2626, 0.1689, 0.0797])
Diff: 0.043200
tensor([0.0929, 0.1826, 0.2134, 0.2627, 0.1688, 0.0796])
Diff: 0.042894
tensor([0.0931, 0.1828, 0.2135, 0.2616, 0.1693, 0.0798])
Diff: 0.043652
tensor([0.0932, 0.1837, 0.2127, 0.2603, 0.1702, 0.0799])
Diff: 0.043794
tensor([0.0930, 0.1832, 0.2126, 0.2616, 0.1698, 0.0798])
Diff: 0.044131
tensor([0.0930, 0.1834, 0.2122, 0.2605, 0.1712, 0.0798])
Diff: 0.044012
tensor([0.0930, 0.1836, 0.2123, 0.2603, 0.1711, 0.0797])
Diff: 0.044553
tensor([0.0929, 0.1834, 0.2118, 0.2605, 0.1716, 0

Diff: 0.045965
tensor([0.0937, 0.1850, 0.2109, 0.2603, 0.1708, 0.0793])
Diff: 0.045939
tensor([0.0937, 0.1843, 0.2108, 0.2613, 0.1707, 0.0792])
Diff: 0.045845
tensor([0.0937, 0.1842, 0.2109, 0.2613, 0.1708, 0.0792])
Diff: 0.045724
tensor([0.0937, 0.1847, 0.2111, 0.2606, 0.1707, 0.0792])
Diff: 0.045306
tensor([0.0938, 0.1846, 0.2115, 0.2601, 0.1710, 0.0792])
Diff: 0.046112
tensor([0.0938, 0.1849, 0.2107, 0.2604, 0.1709, 0.0793])
Diff: 0.046141
tensor([0.0938, 0.1846, 0.2107, 0.2608, 0.1708, 0.0793])
Diff: 0.045094
tensor([0.0939, 0.1849, 0.2117, 0.2594, 0.1707, 0.0793])
Diff: 0.044148
tensor([0.0940, 0.1847, 0.2126, 0.2592, 0.1702, 0.0792])
Diff: 0.043741
tensor([0.0943, 0.1856, 0.2132, 0.2572, 0.1703, 0.0793])
Diff: 0.043907
tensor([0.0943, 0.1850, 0.2129, 0.2578, 0.1706, 0.0794])
Diff: 0.044830
tensor([0.0944, 0.1859, 0.2121, 0.2572, 0.1710, 0.0795])
Diff: 0.045208
tensor([0.0944, 0.1858, 0.2117, 0.2576, 0.1708, 0.0796])
Diff: 0.044740
tensor([0.0942, 0.1858, 0.2122, 0.2573, 0.1709, 0

Diff: 0.047764
tensor([0.0963, 0.1926, 0.2121, 0.2514, 0.1661, 0.0815])
Diff: 0.048159
tensor([0.0962, 0.1936, 0.2123, 0.2503, 0.1661, 0.0815])
Diff: 0.048273
tensor([0.0962, 0.1935, 0.2121, 0.2506, 0.1662, 0.0813])
Diff: 0.047641
tensor([0.0961, 0.1931, 0.2125, 0.2507, 0.1663, 0.0813])
Diff: 0.047744
tensor([0.0960, 0.1934, 0.2126, 0.2502, 0.1664, 0.0814])
Diff: 0.047596
tensor([0.0961, 0.1935, 0.2129, 0.2493, 0.1668, 0.0815])
Diff: 0.047622
tensor([0.0962, 0.1931, 0.2126, 0.2501, 0.1664, 0.0816])
Diff: 0.047870
tensor([0.0960, 0.1931, 0.2122, 0.2506, 0.1665, 0.0815])
Diff: 0.048394
tensor([0.0963, 0.1936, 0.2120, 0.2500, 0.1665, 0.0817])
Diff: 0.046879
tensor([0.0962, 0.1932, 0.2136, 0.2489, 0.1666, 0.0816])
Diff: 0.047299
tensor([0.0961, 0.1938, 0.2136, 0.2480, 0.1668, 0.0816])
Diff: 0.047287
tensor([0.0961, 0.1943, 0.2140, 0.2472, 0.1668, 0.0816])
Diff: 0.047185
tensor([0.0961, 0.1939, 0.2138, 0.2475, 0.1669, 0.0816])
Diff: 0.048216
tensor([0.0963, 0.1942, 0.2127, 0.2480, 0.1670, 0

Diff: 0.029721
tensor([0.0946, 0.1824, 0.2279, 0.2509, 0.1628, 0.0813])
Diff: 0.029558
tensor([0.0946, 0.1829, 0.2284, 0.2501, 0.1627, 0.0813])
Diff: 0.029647
tensor([0.0948, 0.1827, 0.2283, 0.2501, 0.1628, 0.0813])
Diff: 0.029164
tensor([0.0947, 0.1829, 0.2291, 0.2493, 0.1629, 0.0812])
Diff: 0.028586
tensor([0.0946, 0.1826, 0.2296, 0.2490, 0.1628, 0.0813])
Diff: 0.028955
tensor([0.0945, 0.1824, 0.2287, 0.2494, 0.1637, 0.0813])
Diff: 0.029458
tensor([0.0946, 0.1829, 0.2285, 0.2494, 0.1632, 0.0813])
Diff: 0.030250
tensor([0.0947, 0.1831, 0.2276, 0.2499, 0.1635, 0.0813])
Diff: 0.029977
tensor([0.0945, 0.1835, 0.2284, 0.2498, 0.1626, 0.0811])
Diff: 0.029213
tensor([0.0946, 0.1833, 0.2293, 0.2491, 0.1626, 0.0811])
Diff: 0.028627
tensor([0.0945, 0.1829, 0.2298, 0.2489, 0.1629, 0.0810])
Diff: 0.030081
tensor([0.0949, 0.1839, 0.2287, 0.2478, 0.1636, 0.0811])
Diff: 0.030249
tensor([0.0950, 0.1842, 0.2288, 0.2471, 0.1637, 0.0812])
Diff: 0.029839
tensor([0.0951, 0.1839, 0.2293, 0.2462, 0.1642, 0

tensor([0.0947, 0.1784, 0.2245, 0.2566, 0.1660, 0.0800])
Diff: 0.030958
tensor([0.0945, 0.1779, 0.2246, 0.2572, 0.1659, 0.0799])
Diff: 0.031512
tensor([0.0944, 0.1784, 0.2242, 0.2574, 0.1659, 0.0799])
Diff: 0.031545
tensor([0.0942, 0.1783, 0.2240, 0.2572, 0.1665, 0.0798])
Diff: 0.031815
tensor([0.0943, 0.1787, 0.2238, 0.2568, 0.1663, 0.0800])
Diff: 0.032047
tensor([0.0945, 0.1795, 0.2237, 0.2559, 0.1664, 0.0799])
Diff: 0.031846
tensor([0.0945, 0.1799, 0.2240, 0.2553, 0.1663, 0.0800])
Diff: 0.031974
tensor([0.0945, 0.1794, 0.2239, 0.2564, 0.1658, 0.0800])
Diff: 0.032206
tensor([0.0946, 0.1800, 0.2236, 0.2553, 0.1664, 0.0801])
Diff: 0.032066
tensor([0.0946, 0.1799, 0.2237, 0.2550, 0.1669, 0.0800])
Diff: 0.032372
tensor([0.0946, 0.1792, 0.2232, 0.2561, 0.1670, 0.0799])
Diff: 0.031591
tensor([0.0944, 0.1787, 0.2238, 0.2558, 0.1674, 0.0799])
Diff: 0.031604
tensor([0.0943, 0.1783, 0.2237, 0.2563, 0.1676, 0.0798])
Diff: 0.031044
tensor([0.0943, 0.1788, 0.2243, 0.2546, 0.1682, 0.0798])
Diff: 0

Diff: 0.035991
tensor([0.0927, 0.1830, 0.2202, 0.2540, 0.1708, 0.0792])
Diff: 0.036309
tensor([0.0930, 0.1823, 0.2196, 0.2551, 0.1706, 0.0794])
Diff: 0.036194
tensor([0.0929, 0.1822, 0.2197, 0.2558, 0.1701, 0.0793])
Diff: 0.035191
tensor([0.0929, 0.1815, 0.2205, 0.2558, 0.1700, 0.0793])
Diff: 0.035686
tensor([0.0929, 0.1816, 0.2201, 0.2557, 0.1704, 0.0793])
Diff: 0.036095
tensor([0.0929, 0.1825, 0.2199, 0.2547, 0.1706, 0.0795])
Diff: 0.037076
tensor([0.0930, 0.1829, 0.2190, 0.2550, 0.1707, 0.0795])
Diff: 0.036099
tensor([0.0929, 0.1822, 0.2198, 0.2551, 0.1706, 0.0794])
Diff: 0.035549
tensor([0.0929, 0.1822, 0.2203, 0.2542, 0.1710, 0.0794])
Diff: 0.036261
tensor([0.0931, 0.1831, 0.2199, 0.2535, 0.1708, 0.0795])
Diff: 0.036389
tensor([0.0931, 0.1837, 0.2200, 0.2531, 0.1706, 0.0795])
Diff: 0.036080
tensor([0.0931, 0.1832, 0.2202, 0.2535, 0.1705, 0.0795])
Diff: 0.035935
tensor([0.0931, 0.1828, 0.2202, 0.2543, 0.1702, 0.0795])
Diff: 0.035974
tensor([0.0930, 0.1831, 0.2202, 0.2539, 0.1702, 0

Diff: 0.048926
tensor([0.0958, 0.1898, 0.2094, 0.2507, 0.1737, 0.0807])
Diff: 0.049142
tensor([0.0959, 0.1901, 0.2093, 0.2506, 0.1735, 0.0807])
Diff: 0.048868
tensor([0.0956, 0.1899, 0.2094, 0.2519, 0.1728, 0.0805])
Diff: 0.048181
tensor([0.0956, 0.1895, 0.2100, 0.2512, 0.1732, 0.0805])
Diff: 0.047826
tensor([0.0954, 0.1895, 0.2104, 0.2513, 0.1730, 0.0805])
Diff: 0.046938
tensor([0.0954, 0.1894, 0.2114, 0.2500, 0.1732, 0.0805])
Diff: 0.047543
tensor([0.0957, 0.1898, 0.2110, 0.2496, 0.1733, 0.0805])
Diff: 0.047311
tensor([0.0959, 0.1895, 0.2112, 0.2489, 0.1736, 0.0808])
Diff: 0.047324
tensor([0.0960, 0.1896, 0.2114, 0.2480, 0.1740, 0.0810])
Diff: 0.047287
tensor([0.0961, 0.1896, 0.2114, 0.2482, 0.1738, 0.0810])
Diff: 0.048117
tensor([0.0961, 0.1903, 0.2108, 0.2481, 0.1738, 0.0810])
Diff: 0.047642
tensor([0.0961, 0.1901, 0.2112, 0.2480, 0.1736, 0.0810])
Diff: 0.047228
tensor([0.0962, 0.1902, 0.2121, 0.2463, 0.1742, 0.0810])
Diff: 0.047396
tensor([0.0964, 0.1902, 0.2119, 0.2466, 0.1739, 0

tensor([0.0980, 0.1913, 0.2071, 0.2395, 0.1816, 0.0825])
Diff: 0.054384
tensor([0.0979, 0.1912, 0.2076, 0.2390, 0.1817, 0.0826])
Diff: 0.053317
tensor([0.0980, 0.1908, 0.2088, 0.2386, 0.1812, 0.0825])
Diff: 0.052958
tensor([0.0979, 0.1907, 0.2091, 0.2385, 0.1812, 0.0825])
Diff: 0.052421
tensor([0.0979, 0.1901, 0.2097, 0.2381, 0.1817, 0.0825])
Diff: 0.052665
tensor([0.0978, 0.1902, 0.2099, 0.2373, 0.1823, 0.0825])
Diff: 0.052689
tensor([0.0979, 0.1904, 0.2100, 0.2372, 0.1820, 0.0825])
Diff: 0.052510
tensor([0.0979, 0.1901, 0.2106, 0.2363, 0.1825, 0.0826])
Diff: 0.052553
tensor([0.0978, 0.1902, 0.2104, 0.2366, 0.1824, 0.0825])
Diff: 0.052126
tensor([0.0978, 0.1897, 0.2108, 0.2366, 0.1827, 0.0825])
Diff: 0.052201
tensor([0.0977, 0.1898, 0.2106, 0.2369, 0.1826, 0.0824])
Diff: 0.052751
tensor([0.0976, 0.1896, 0.2101, 0.2366, 0.1834, 0.0826])
Diff: 0.052239
tensor([0.0976, 0.1903, 0.2111, 0.2358, 0.1827, 0.0825])
Diff: 0.052906
tensor([0.0979, 0.1907, 0.2109, 0.2352, 0.1828, 0.0825])
Diff: 0

Diff: 0.039793
tensor([0.0962, 0.1865, 0.2206, 0.2407, 0.1749, 0.0811])
Diff: 0.039634
tensor([0.0962, 0.1864, 0.2209, 0.2404, 0.1749, 0.0811])
Diff: 0.039029
tensor([0.0960, 0.1859, 0.2213, 0.2406, 0.1753, 0.0808])
Diff: 0.039469
tensor([0.0960, 0.1864, 0.2211, 0.2404, 0.1753, 0.0809])
Diff: 0.039037
tensor([0.0960, 0.1860, 0.2214, 0.2405, 0.1753, 0.0809])
Diff: 0.038787
tensor([0.0960, 0.1860, 0.2217, 0.2403, 0.1750, 0.0809])
Diff: 0.038764
tensor([0.0961, 0.1866, 0.2230, 0.2384, 0.1751, 0.0809])
Diff: 0.038904
tensor([0.0962, 0.1864, 0.2231, 0.2378, 0.1756, 0.0810])
Diff: 0.039344
tensor([0.0962, 0.1869, 0.2230, 0.2374, 0.1755, 0.0811])
Diff: 0.040022
tensor([0.0963, 0.1877, 0.2226, 0.2371, 0.1750, 0.0813])
Diff: 0.040265
tensor([0.0964, 0.1877, 0.2219, 0.2379, 0.1749, 0.0812])
Diff: 0.040434
tensor([0.0964, 0.1877, 0.2209, 0.2393, 0.1743, 0.0813])
Diff: 0.040229
tensor([0.0963, 0.1868, 0.2198, 0.2417, 0.1743, 0.0811])
Diff: 0.039856
tensor([0.0964, 0.1866, 0.2203, 0.2412, 0.1744, 0

Diff: 0.041458
tensor([0.0976, 0.1880, 0.2193, 0.2410, 0.1726, 0.0814])
Diff: 0.041260
tensor([0.0975, 0.1885, 0.2203, 0.2398, 0.1725, 0.0814])
Diff: 0.041104
tensor([0.0974, 0.1887, 0.2203, 0.2404, 0.1719, 0.0814])
Diff: 0.041220
tensor([0.0973, 0.1888, 0.2205, 0.2398, 0.1723, 0.0813])
Diff: 0.040288
tensor([0.0976, 0.1886, 0.2224, 0.2381, 0.1721, 0.0812])
Diff: 0.040385
tensor([0.0975, 0.1889, 0.2224, 0.2380, 0.1720, 0.0812])
Diff: 0.040687
tensor([0.0975, 0.1890, 0.2222, 0.2378, 0.1722, 0.0812])
Diff: 0.040942
tensor([0.0973, 0.1891, 0.2212, 0.2394, 0.1722, 0.0809])
Diff: 0.041204
tensor([0.0973, 0.1888, 0.2203, 0.2405, 0.1724, 0.0808])
Diff: 0.041263
tensor([0.0971, 0.1889, 0.2196, 0.2421, 0.1717, 0.0807])
Diff: 0.041665
tensor([0.0971, 0.1888, 0.2191, 0.2422, 0.1723, 0.0805])
Diff: 0.041242
tensor([0.0970, 0.1884, 0.2189, 0.2434, 0.1715, 0.0807])
Diff: 0.041192
tensor([0.0971, 0.1884, 0.2190, 0.2435, 0.1716, 0.0805])
Diff: 0.041033
tensor([0.0971, 0.1883, 0.2191, 0.2435, 0.1714, 0

Diff: 0.040118
tensor([0.0976, 0.1872, 0.2228, 0.2365, 0.1744, 0.0815])
Diff: 0.039682
tensor([0.0977, 0.1870, 0.2235, 0.2362, 0.1742, 0.0815])
Diff: 0.039437
tensor([0.0977, 0.1868, 0.2239, 0.2359, 0.1744, 0.0814])
Diff: 0.039584
tensor([0.0977, 0.1865, 0.2235, 0.2361, 0.1748, 0.0814])
Diff: 0.038645
tensor([0.0976, 0.1861, 0.2241, 0.2366, 0.1742, 0.0814])
Diff: 0.038533
tensor([0.0976, 0.1864, 0.2251, 0.2355, 0.1742, 0.0814])
Diff: 0.037833
tensor([0.0976, 0.1856, 0.2262, 0.2346, 0.1747, 0.0814])
Diff: 0.038407
tensor([0.0974, 0.1863, 0.2261, 0.2341, 0.1747, 0.0814])
Diff: 0.038454
tensor([0.0973, 0.1863, 0.2249, 0.2357, 0.1744, 0.0813])
Diff: 0.038589
tensor([0.0975, 0.1867, 0.2255, 0.2349, 0.1741, 0.0813])
Diff: 0.038282
tensor([0.0973, 0.1865, 0.2254, 0.2354, 0.1742, 0.0812])
Diff: 0.038519
tensor([0.0974, 0.1861, 0.2260, 0.2341, 0.1750, 0.0813])
Diff: 0.038532
tensor([0.0974, 0.1864, 0.2268, 0.2332, 0.1749, 0.0812])
Diff: 0.037721
tensor([0.0975, 0.1861, 0.2280, 0.2327, 0.1743, 0

Diff: 0.052824
tensor([0.0990, 0.1860, 0.2281, 0.2160, 0.1897, 0.0811])
Diff: 0.053118
tensor([0.0991, 0.1861, 0.2283, 0.2156, 0.1897, 0.0812])
Diff: 0.051301
tensor([0.0989, 0.1856, 0.2283, 0.2173, 0.1887, 0.0811])
Diff: 0.051233
tensor([0.0988, 0.1852, 0.2284, 0.2174, 0.1892, 0.0810])
Diff: 0.051167
tensor([0.0988, 0.1853, 0.2294, 0.2167, 0.1888, 0.0810])
Diff: 0.050047
tensor([0.0988, 0.1850, 0.2296, 0.2175, 0.1879, 0.0810])
Diff: 0.050446
tensor([0.0990, 0.1849, 0.2292, 0.2174, 0.1883, 0.0811])
Diff: 0.050035
tensor([0.0989, 0.1849, 0.2291, 0.2180, 0.1881, 0.0811])
Diff: 0.048834
tensor([0.0987, 0.1837, 0.2307, 0.2180, 0.1880, 0.0809])
Diff: 0.049427
tensor([0.0986, 0.1837, 0.2306, 0.2176, 0.1886, 0.0809])
Diff: 0.050291
tensor([0.0987, 0.1842, 0.2292, 0.2177, 0.1892, 0.0809])
Diff: 0.050547
tensor([0.0988, 0.1842, 0.2282, 0.2183, 0.1895, 0.0809])
Diff: 0.051157
tensor([0.0989, 0.1839, 0.2275, 0.2183, 0.1903, 0.0810])
Diff: 0.052372
tensor([0.0991, 0.1841, 0.2273, 0.2172, 0.1911, 0

Diff: 0.054579
tensor([0.1006, 0.1823, 0.2200, 0.2220, 0.1940, 0.0810])
Diff: 0.054219
tensor([0.1008, 0.1825, 0.2194, 0.2230, 0.1934, 0.0810])
Diff: 0.053999
tensor([0.1009, 0.1821, 0.2187, 0.2239, 0.1932, 0.0811])
Diff: 0.054021
tensor([0.1008, 0.1821, 0.2196, 0.2230, 0.1934, 0.0811])
Diff: 0.053632
tensor([0.1009, 0.1821, 0.2207, 0.2222, 0.1930, 0.0811])
Diff: 0.053673
tensor([0.1009, 0.1826, 0.2195, 0.2234, 0.1927, 0.0810])
Diff: 0.053601
tensor([0.1008, 0.1826, 0.2188, 0.2243, 0.1926, 0.0809])
Diff: 0.053243
tensor([0.1007, 0.1823, 0.2191, 0.2243, 0.1926, 0.0809])
Diff: 0.053453
tensor([0.1008, 0.1827, 0.2193, 0.2239, 0.1924, 0.0810])
Diff: 0.052292
tensor([0.1007, 0.1823, 0.2187, 0.2259, 0.1916, 0.0808])
Diff: 0.052456
tensor([0.1007, 0.1823, 0.2187, 0.2257, 0.1917, 0.0809])
Diff: 0.052692
tensor([0.1008, 0.1822, 0.2183, 0.2259, 0.1919, 0.0809])
Diff: 0.052600
tensor([0.1007, 0.1823, 0.2188, 0.2254, 0.1919, 0.0809])
Diff: 0.053660
tensor([0.1008, 0.1825, 0.2188, 0.2242, 0.1927, 0

Diff: 0.060106
tensor([0.0991, 0.1843, 0.2232, 0.2145, 0.1992, 0.0797])
Diff: 0.058867
tensor([0.0990, 0.1840, 0.2229, 0.2159, 0.1984, 0.0797])
Diff: 0.058557
tensor([0.0989, 0.1836, 0.2226, 0.2166, 0.1986, 0.0798])
Diff: 0.057926
tensor([0.0989, 0.1832, 0.2233, 0.2166, 0.1983, 0.0797])
Diff: 0.057525
tensor([0.0988, 0.1836, 0.2234, 0.2168, 0.1976, 0.0797])
Diff: 0.057437
tensor([0.0986, 0.1838, 0.2245, 0.2160, 0.1975, 0.0795])
Diff: 0.056654
tensor([0.0985, 0.1833, 0.2253, 0.2162, 0.1972, 0.0795])
Diff: 0.058017
tensor([0.0988, 0.1833, 0.2245, 0.2156, 0.1983, 0.0796])
Diff: 0.057913
tensor([0.0987, 0.1839, 0.2243, 0.2157, 0.1978, 0.0796])
Diff: 0.057996
tensor([0.0988, 0.1842, 0.2237, 0.2160, 0.1976, 0.0797])
Diff: 0.057204
tensor([0.0987, 0.1836, 0.2231, 0.2174, 0.1975, 0.0796])
Diff: 0.057147
tensor([0.0989, 0.1836, 0.2222, 0.2183, 0.1974, 0.0797])
Diff: 0.057353
tensor([0.0989, 0.1832, 0.2226, 0.2177, 0.1978, 0.0798])
Diff: 0.058820
tensor([0.0991, 0.1839, 0.2215, 0.2171, 0.1983, 0

Diff: 0.055711
tensor([0.0977, 0.1823, 0.2278, 0.2151, 0.1971, 0.0800])
Diff: 0.055065
tensor([0.0974, 0.1823, 0.2283, 0.2153, 0.1967, 0.0800])
Diff: 0.056147
tensor([0.0975, 0.1825, 0.2290, 0.2138, 0.1972, 0.0800])
Diff: 0.055167
tensor([0.0977, 0.1815, 0.2293, 0.2145, 0.1970, 0.0801])
Diff: 0.055655
tensor([0.0975, 0.1819, 0.2284, 0.2148, 0.1974, 0.0801])
Diff: 0.056287
tensor([0.0976, 0.1829, 0.2280, 0.2142, 0.1971, 0.0802])
Diff: 0.055714
tensor([0.0975, 0.1823, 0.2285, 0.2144, 0.1970, 0.0803])
Diff: 0.056045
tensor([0.0975, 0.1827, 0.2291, 0.2136, 0.1969, 0.0802])
Diff: 0.056022
tensor([0.0974, 0.1820, 0.2295, 0.2136, 0.1975, 0.0800])
Diff: 0.056411
tensor([0.0975, 0.1825, 0.2294, 0.2132, 0.1973, 0.0800])
Diff: 0.056679
tensor([0.0975, 0.1823, 0.2295, 0.2130, 0.1977, 0.0800])
Diff: 0.056914
tensor([0.0977, 0.1822, 0.2304, 0.2121, 0.1976, 0.0800])
Diff: 0.057661
tensor([0.0976, 0.1828, 0.2296, 0.2119, 0.1980, 0.0800])
Diff: 0.057737
tensor([0.0976, 0.1828, 0.2295, 0.2119, 0.1981, 0

Diff: 0.058143
tensor([0.0951, 0.1741, 0.2216, 0.2228, 0.2070, 0.0793])
Diff: 0.057518
tensor([0.0951, 0.1736, 0.2222, 0.2231, 0.2067, 0.0793])
Diff: 0.057562
tensor([0.0950, 0.1731, 0.2229, 0.2226, 0.2071, 0.0792])
Diff: 0.057967
tensor([0.0949, 0.1733, 0.2229, 0.2223, 0.2074, 0.0791])
Diff: 0.057521
tensor([0.0950, 0.1736, 0.2231, 0.2224, 0.2069, 0.0791])
Diff: 0.058311
tensor([0.0951, 0.1734, 0.2228, 0.2219, 0.2076, 0.0792])
Diff: 0.057374
tensor([0.0948, 0.1734, 0.2231, 0.2226, 0.2069, 0.0791])
Diff: 0.058861
tensor([0.0949, 0.1729, 0.2224, 0.2221, 0.2083, 0.0794])
Diff: 0.058001
tensor([0.0951, 0.1728, 0.2230, 0.2222, 0.2075, 0.0794])
Diff: 0.058696
tensor([0.0951, 0.1734, 0.2225, 0.2218, 0.2078, 0.0794])
Diff: 0.058243
tensor([0.0949, 0.1738, 0.2226, 0.2220, 0.2073, 0.0793])
Diff: 0.058749
tensor([0.0949, 0.1741, 0.2227, 0.2214, 0.2077, 0.0792])
Diff: 0.059701
tensor([0.0948, 0.1745, 0.2226, 0.2205, 0.2083, 0.0793])
Diff: 0.059407
tensor([0.0949, 0.1744, 0.2226, 0.2207, 0.2080, 0

tensor([0.0953, 0.1722, 0.2315, 0.2219, 0.2015, 0.0776])
Diff: 0.050605
tensor([0.0952, 0.1727, 0.2317, 0.2215, 0.2014, 0.0776])
Diff: 0.050879
tensor([0.0951, 0.1732, 0.2320, 0.2208, 0.2013, 0.0776])
Diff: 0.050302
tensor([0.0952, 0.1728, 0.2320, 0.2215, 0.2010, 0.0776])
Diff: 0.050177
tensor([0.0951, 0.1731, 0.2328, 0.2208, 0.2007, 0.0775])
Diff: 0.050493
tensor([0.0949, 0.1729, 0.2330, 0.2206, 0.2011, 0.0774])
Diff: 0.048853
tensor([0.0947, 0.1724, 0.2356, 0.2202, 0.1997, 0.0773])
Diff: 0.048500
tensor([0.0947, 0.1727, 0.2355, 0.2204, 0.1993, 0.0773])
Diff: 0.047957
tensor([0.0947, 0.1725, 0.2360, 0.2206, 0.1989, 0.0773])
Diff: 0.047887
tensor([0.0949, 0.1732, 0.2352, 0.2208, 0.1985, 0.0774])
Diff: 0.046698
tensor([0.0948, 0.1727, 0.2356, 0.2217, 0.1978, 0.0774])
Diff: 0.047251
tensor([0.0949, 0.1729, 0.2356, 0.2212, 0.1981, 0.0773])
Diff: 0.047747
tensor([0.0948, 0.1724, 0.2349, 0.2216, 0.1990, 0.0772])
Diff: 0.046805
tensor([0.0947, 0.1723, 0.2349, 0.2226, 0.1985, 0.0770])
Diff: 0

tensor([0.0957, 0.1662, 0.2373, 0.2239, 0.2000, 0.0769])
Diff: 0.046685
tensor([0.0956, 0.1659, 0.2362, 0.2247, 0.2007, 0.0769])
Diff: 0.046607
tensor([0.0956, 0.1662, 0.2363, 0.2245, 0.2005, 0.0770])
Diff: 0.046622
tensor([0.0955, 0.1661, 0.2360, 0.2246, 0.2005, 0.0771])
Diff: 0.046963
tensor([0.0955, 0.1659, 0.2356, 0.2250, 0.2011, 0.0770])
Diff: 0.047676
tensor([0.0956, 0.1663, 0.2361, 0.2237, 0.2013, 0.0771])
Diff: 0.048823
tensor([0.0956, 0.1668, 0.2351, 0.2232, 0.2021, 0.0772])
Diff: 0.048662
tensor([0.0957, 0.1670, 0.2343, 0.2238, 0.2019, 0.0773])
Diff: 0.049217
tensor([0.0959, 0.1670, 0.2335, 0.2238, 0.2024, 0.0774])
Diff: 0.048790
tensor([0.0958, 0.1673, 0.2345, 0.2233, 0.2018, 0.0773])
Diff: 0.048635
tensor([0.0960, 0.1667, 0.2342, 0.2239, 0.2019, 0.0773])
Diff: 0.049451
tensor([0.0960, 0.1663, 0.2344, 0.2233, 0.2026, 0.0773])
Diff: 0.050590
tensor([0.0960, 0.1660, 0.2340, 0.2228, 0.2037, 0.0774])
Diff: 0.050440
tensor([0.0961, 0.1666, 0.2330, 0.2233, 0.2034, 0.0776])
Diff: 0

tensor([0.0956, 0.1677, 0.2290, 0.2191, 0.2106, 0.0780])
Diff: 0.060520
tensor([0.0955, 0.1681, 0.2301, 0.2171, 0.2114, 0.0778])
Diff: 0.061133
tensor([0.0956, 0.1679, 0.2303, 0.2165, 0.2119, 0.0778])
Diff: 0.062161
tensor([0.0957, 0.1677, 0.2293, 0.2166, 0.2129, 0.0779])
Diff: 0.061911
tensor([0.0958, 0.1683, 0.2294, 0.2162, 0.2123, 0.0780])
Diff: 0.063064
tensor([0.0957, 0.1682, 0.2298, 0.2151, 0.2132, 0.0779])
Diff: 0.062623
tensor([0.0957, 0.1688, 0.2301, 0.2149, 0.2126, 0.0779])
Diff: 0.062841
tensor([0.0958, 0.1689, 0.2295, 0.2150, 0.2127, 0.0780])
Diff: 0.063000
tensor([0.0956, 0.1690, 0.2283, 0.2159, 0.2131, 0.0781])
Diff: 0.063034
tensor([0.0955, 0.1687, 0.2281, 0.2162, 0.2133, 0.0782])
Diff: 0.062160
tensor([0.0954, 0.1683, 0.2290, 0.2164, 0.2127, 0.0782])
Diff: 0.062818
tensor([0.0955, 0.1682, 0.2288, 0.2161, 0.2133, 0.0782])
Diff: 0.063000
tensor([0.0957, 0.1685, 0.2286, 0.2159, 0.2132, 0.0782])
Diff: 0.062941
tensor([0.0957, 0.1683, 0.2284, 0.2161, 0.2132, 0.0783])
Diff: 0

Diff: 0.064049
tensor([0.0951, 0.1668, 0.2333, 0.2118, 0.2137, 0.0793])
Diff: 0.062705
tensor([0.0951, 0.1665, 0.2342, 0.2123, 0.2126, 0.0793])
Diff: 0.063469
tensor([0.0952, 0.1663, 0.2356, 0.2109, 0.2128, 0.0793])
Diff: 0.063844
tensor([0.0952, 0.1664, 0.2354, 0.2106, 0.2131, 0.0793])
Diff: 0.063878
tensor([0.0952, 0.1664, 0.2355, 0.2105, 0.2131, 0.0792])
Diff: 0.064889
tensor([0.0953, 0.1670, 0.2353, 0.2097, 0.2137, 0.0792])
Diff: 0.065779
tensor([0.0953, 0.1672, 0.2359, 0.2084, 0.2140, 0.0792])
Diff: 0.064875
tensor([0.0953, 0.1676, 0.2354, 0.2093, 0.2133, 0.0791])
Diff: 0.064602
tensor([0.0952, 0.1674, 0.2359, 0.2092, 0.2131, 0.0792])
Diff: 0.064788
tensor([0.0955, 0.1679, 0.2356, 0.2089, 0.2129, 0.0792])
Diff: 0.064886
tensor([0.0956, 0.1682, 0.2351, 0.2089, 0.2128, 0.0793])
Diff: 0.064544
tensor([0.0956, 0.1684, 0.2350, 0.2091, 0.2125, 0.0794])
Diff: 0.064371
tensor([0.0956, 0.1679, 0.2361, 0.2088, 0.2123, 0.0794])
Diff: 0.064613
tensor([0.0956, 0.1675, 0.2360, 0.2088, 0.2126, 0

Diff: 0.059996
tensor([0.0961, 0.1694, 0.2255, 0.2193, 0.2099, 0.0797])
Diff: 0.060721
tensor([0.0963, 0.1696, 0.2247, 0.2192, 0.2104, 0.0799])
Diff: 0.059911
tensor([0.0962, 0.1694, 0.2256, 0.2191, 0.2098, 0.0799])
Diff: 0.060345
tensor([0.0963, 0.1702, 0.2247, 0.2192, 0.2098, 0.0798])
Diff: 0.060155
tensor([0.0963, 0.1704, 0.2252, 0.2187, 0.2095, 0.0798])
Diff: 0.060610
tensor([0.0965, 0.1705, 0.2238, 0.2195, 0.2098, 0.0800])
Diff: 0.060798
tensor([0.0966, 0.1704, 0.2237, 0.2194, 0.2099, 0.0800])
Diff: 0.060369
tensor([0.0967, 0.1705, 0.2239, 0.2194, 0.2094, 0.0800])
Diff: 0.060278
tensor([0.0966, 0.1706, 0.2230, 0.2205, 0.2095, 0.0799])
Diff: 0.060227
tensor([0.0967, 0.1706, 0.2223, 0.2211, 0.2093, 0.0798])
Diff: 0.059659
tensor([0.0965, 0.1700, 0.2229, 0.2217, 0.2094, 0.0797])
Diff: 0.060128
tensor([0.0965, 0.1707, 0.2215, 0.2222, 0.2094, 0.0797])
Diff: 0.059996
tensor([0.0964, 0.1709, 0.2221, 0.2217, 0.2093, 0.0796])
Diff: 0.059710
tensor([0.0964, 0.1704, 0.2218, 0.2226, 0.2093, 0

tensor([0.0948, 0.1706, 0.2304, 0.2057, 0.2208, 0.0777])
Diff: 0.074311
tensor([0.0948, 0.1706, 0.2296, 0.2059, 0.2213, 0.0778])
Diff: 0.074928
tensor([0.0948, 0.1707, 0.2297, 0.2054, 0.2217, 0.0777])
Diff: 0.076081
tensor([0.0949, 0.1705, 0.2295, 0.2046, 0.2226, 0.0778])
Diff: 0.075717
tensor([0.0948, 0.1699, 0.2300, 0.2049, 0.2226, 0.0778])
Diff: 0.075059
tensor([0.0947, 0.1708, 0.2300, 0.2049, 0.2216, 0.0780])
Diff: 0.074742
tensor([0.0945, 0.1711, 0.2305, 0.2048, 0.2213, 0.0778])
Diff: 0.075462
tensor([0.0944, 0.1713, 0.2310, 0.2039, 0.2217, 0.0777])
Diff: 0.075453
tensor([0.0944, 0.1709, 0.2305, 0.2044, 0.2220, 0.0777])
Diff: 0.076585
tensor([0.0945, 0.1713, 0.2302, 0.2036, 0.2227, 0.0777])
Diff: 0.076987
tensor([0.0945, 0.1717, 0.2300, 0.2033, 0.2229, 0.0776])
Diff: 0.076429
tensor([0.0946, 0.1723, 0.2291, 0.2040, 0.2223, 0.0777])
Diff: 0.075463
tensor([0.0945, 0.1724, 0.2289, 0.2049, 0.2217, 0.0776])
Diff: 0.075573
tensor([0.0944, 0.1719, 0.2293, 0.2049, 0.2220, 0.0776])
Diff: 0

Diff: 0.083053
tensor([0.0949, 0.1765, 0.2161, 0.2069, 0.2270, 0.0786])
Diff: 0.082541
tensor([0.0948, 0.1765, 0.2164, 0.2071, 0.2266, 0.0785])
Diff: 0.081944
tensor([0.0948, 0.1763, 0.2165, 0.2077, 0.2263, 0.0785])
Diff: 0.082569
tensor([0.0948, 0.1766, 0.2164, 0.2070, 0.2266, 0.0785])
Diff: 0.082098
tensor([0.0948, 0.1768, 0.2175, 0.2065, 0.2261, 0.0783])
Diff: 0.081466
tensor([0.0948, 0.1766, 0.2177, 0.2069, 0.2256, 0.0784])
Diff: 0.080499
tensor([0.0948, 0.1764, 0.2192, 0.2064, 0.2248, 0.0783])
Diff: 0.079438
tensor([0.0947, 0.1763, 0.2202, 0.2065, 0.2240, 0.0783])
Diff: 0.079657
tensor([0.0949, 0.1763, 0.2207, 0.2058, 0.2239, 0.0784])
Diff: 0.078543
tensor([0.0946, 0.1764, 0.2212, 0.2064, 0.2232, 0.0782])
Diff: 0.078257
tensor([0.0946, 0.1760, 0.2213, 0.2068, 0.2232, 0.0782])
Diff: 0.079075
tensor([0.0946, 0.1767, 0.2210, 0.2061, 0.2235, 0.0782])
Diff: 0.079404
tensor([0.0944, 0.1770, 0.2210, 0.2058, 0.2237, 0.0780])
Diff: 0.079657
tensor([0.0944, 0.1775, 0.2211, 0.2053, 0.2236, 0

Diff: 0.086475
tensor([0.0970, 0.1837, 0.2200, 0.1961, 0.2231, 0.0802])
Diff: 0.086135
tensor([0.0970, 0.1831, 0.2205, 0.1962, 0.2231, 0.0801])
Diff: 0.084963
tensor([0.0971, 0.1825, 0.2204, 0.1973, 0.2224, 0.0803])
Diff: 0.085934
tensor([0.0973, 0.1830, 0.2202, 0.1963, 0.2228, 0.0804])
Diff: 0.086647
tensor([0.0973, 0.1833, 0.2198, 0.1960, 0.2232, 0.0804])
Diff: 0.087006
tensor([0.0973, 0.1830, 0.2193, 0.1961, 0.2238, 0.0805])
Diff: 0.086640
tensor([0.0975, 0.1826, 0.2204, 0.1956, 0.2233, 0.0806])
Diff: 0.088313
tensor([0.0974, 0.1821, 0.2192, 0.1954, 0.2252, 0.0808])
Diff: 0.087848
tensor([0.0973, 0.1819, 0.2195, 0.1956, 0.2250, 0.0808])
Diff: 0.088380
tensor([0.0973, 0.1826, 0.2184, 0.1957, 0.2251, 0.0809])
Diff: 0.087243
tensor([0.0971, 0.1821, 0.2202, 0.1955, 0.2243, 0.0808])
Diff: 0.087413
tensor([0.0973, 0.1822, 0.2200, 0.1954, 0.2243, 0.0809])
Diff: 0.087196
tensor([0.0971, 0.1816, 0.2206, 0.1955, 0.2245, 0.0806])
Diff: 0.087180
tensor([0.0972, 0.1816, 0.2205, 0.1955, 0.2245, 0

Diff: 0.083834
tensor([0.0978, 0.1788, 0.2246, 0.1957, 0.2221, 0.0809])
Diff: 0.082891
tensor([0.0977, 0.1787, 0.2248, 0.1964, 0.2215, 0.0809])
Diff: 0.082928
tensor([0.0976, 0.1790, 0.2241, 0.1968, 0.2216, 0.0809])
Diff: 0.082996
tensor([0.0977, 0.1786, 0.2244, 0.1966, 0.2217, 0.0810])
Diff: 0.083769
tensor([0.0978, 0.1784, 0.2250, 0.1957, 0.2223, 0.0809])
Diff: 0.083233
tensor([0.0977, 0.1782, 0.2256, 0.1958, 0.2219, 0.0808])
Diff: 0.082429
tensor([0.0976, 0.1780, 0.2261, 0.1962, 0.2214, 0.0807])
Diff: 0.082786
tensor([0.0977, 0.1777, 0.2266, 0.1957, 0.2216, 0.0807])
Diff: 0.082272
tensor([0.0977, 0.1772, 0.2264, 0.1965, 0.2216, 0.0806])
Diff: 0.081995
tensor([0.0977, 0.1780, 0.2268, 0.1961, 0.2209, 0.0806])
Diff: 0.081927
tensor([0.0975, 0.1774, 0.2279, 0.1957, 0.2210, 0.0805])
Diff: 0.081335
tensor([0.0975, 0.1775, 0.2290, 0.1954, 0.2202, 0.0805])
Diff: 0.082318
tensor([0.0976, 0.1777, 0.2285, 0.1948, 0.2209, 0.0805])
Diff: 0.081936
tensor([0.0976, 0.1772, 0.2291, 0.1948, 0.2206, 0

tensor([0.0994, 0.1807, 0.2372, 0.1773, 0.2235, 0.0819])
Diff: 0.096507
tensor([0.0995, 0.1814, 0.2366, 0.1767, 0.2239, 0.0819])
Diff: 0.095917
tensor([0.0994, 0.1821, 0.2360, 0.1773, 0.2234, 0.0818])
Diff: 0.096348
tensor([0.0993, 0.1815, 0.2369, 0.1767, 0.2238, 0.0818])
Diff: 0.095172
tensor([0.0992, 0.1816, 0.2369, 0.1776, 0.2229, 0.0818])
Diff: 0.095201
tensor([0.0990, 0.1817, 0.2366, 0.1778, 0.2232, 0.0816])
Diff: 0.094703
tensor([0.0989, 0.1816, 0.2373, 0.1779, 0.2227, 0.0816])
Diff: 0.095048
tensor([0.0989, 0.1815, 0.2373, 0.1777, 0.2230, 0.0816])
Diff: 0.095353
tensor([0.0989, 0.1817, 0.2377, 0.1772, 0.2229, 0.0815])
Diff: 0.095401
tensor([0.0989, 0.1815, 0.2381, 0.1770, 0.2230, 0.0815])
Diff: 0.095817
tensor([0.0988, 0.1808, 0.2389, 0.1765, 0.2234, 0.0816])
Diff: 0.095094
tensor([0.0987, 0.1804, 0.2407, 0.1763, 0.2223, 0.0815])
Diff: 0.094992
tensor([0.0988, 0.1809, 0.2405, 0.1763, 0.2219, 0.0816])
Diff: 0.094428
tensor([0.0988, 0.1806, 0.2400, 0.1770, 0.2219, 0.0816])
Diff: 0

Diff: 0.096664
tensor([0.0983, 0.1845, 0.2432, 0.1725, 0.2191, 0.0823])
Diff: 0.097051
tensor([0.0983, 0.1844, 0.2441, 0.1719, 0.2190, 0.0823])
Diff: 0.097861
tensor([0.0983, 0.1844, 0.2447, 0.1710, 0.2194, 0.0822])
Diff: 0.097967
tensor([0.0982, 0.1840, 0.2446, 0.1712, 0.2199, 0.0822])
Diff: 0.097332
tensor([0.0983, 0.1842, 0.2438, 0.1719, 0.2196, 0.0822])
Diff: 0.097611
tensor([0.0983, 0.1836, 0.2445, 0.1715, 0.2198, 0.0822])
Diff: 0.098320
tensor([0.0983, 0.1843, 0.2441, 0.1709, 0.2200, 0.0824])
Diff: 0.098828
tensor([0.0985, 0.1849, 0.2439, 0.1704, 0.2199, 0.0824])
Diff: 0.098546
tensor([0.0984, 0.1855, 0.2441, 0.1704, 0.2192, 0.0823])
Diff: 0.098192
tensor([0.0985, 0.1860, 0.2455, 0.1700, 0.2178, 0.0823])
Diff: 0.098220
tensor([0.0984, 0.1860, 0.2452, 0.1701, 0.2180, 0.0823])
Diff: 0.098644
tensor([0.0986, 0.1853, 0.2457, 0.1697, 0.2184, 0.0822])
Diff: 0.099191
tensor([0.0987, 0.1856, 0.2458, 0.1691, 0.2185, 0.0823])
Diff: 0.099271
tensor([0.0987, 0.1854, 0.2460, 0.1691, 0.2186, 0

Diff: 0.107201
tensor([0.0979, 0.1956, 0.2255, 0.1715, 0.2273, 0.0822])
Diff: 0.107056
tensor([0.0981, 0.1956, 0.2248, 0.1719, 0.2273, 0.0823])
Diff: 0.107407
tensor([0.0980, 0.1951, 0.2262, 0.1710, 0.2275, 0.0822])
Diff: 0.107853
tensor([0.0979, 0.1949, 0.2266, 0.1705, 0.2279, 0.0821])
Diff: 0.108704
tensor([0.0979, 0.1958, 0.2263, 0.1698, 0.2280, 0.0823])
Diff: 0.109563
tensor([0.0979, 0.1954, 0.2265, 0.1691, 0.2288, 0.0823])
Diff: 0.109560
tensor([0.0979, 0.1948, 0.2266, 0.1691, 0.2292, 0.0823])
Diff: 0.110133
tensor([0.0979, 0.1957, 0.2265, 0.1686, 0.2290, 0.0822])
Diff: 0.110565
tensor([0.0978, 0.1958, 0.2265, 0.1683, 0.2294, 0.0822])
Diff: 0.109542
tensor([0.0978, 0.1957, 0.2265, 0.1691, 0.2287, 0.0822])
Diff: 0.110176
tensor([0.0979, 0.1959, 0.2260, 0.1688, 0.2291, 0.0823])
Diff: 0.110146
tensor([0.0977, 0.1958, 0.2264, 0.1687, 0.2292, 0.0823])
Diff: 0.110611
tensor([0.0977, 0.1953, 0.2259, 0.1687, 0.2301, 0.0823])
Diff: 0.111537
tensor([0.0977, 0.1962, 0.2250, 0.1684, 0.2305, 0

tensor([0.0975, 0.1958, 0.2298, 0.1653, 0.2305, 0.0811])
Diff: 0.112279
tensor([0.0975, 0.1965, 0.2292, 0.1658, 0.2298, 0.0812])
Diff: 0.112705
tensor([0.0976, 0.1965, 0.2294, 0.1653, 0.2300, 0.0812])
Diff: 0.111964
tensor([0.0975, 0.1959, 0.2300, 0.1657, 0.2297, 0.0812])
Diff: 0.112043
tensor([0.0976, 0.1967, 0.2292, 0.1659, 0.2294, 0.0813])
Diff: 0.112453
tensor([0.0977, 0.1972, 0.2297, 0.1651, 0.2290, 0.0813])
Diff: 0.113203
tensor([0.0977, 0.1973, 0.2295, 0.1647, 0.2296, 0.0812])
Diff: 0.113376
tensor([0.0975, 0.1975, 0.2286, 0.1651, 0.2301, 0.0812])
Diff: 0.113490
tensor([0.0976, 0.1978, 0.2285, 0.1648, 0.2298, 0.0814])
Diff: 0.113777
tensor([0.0978, 0.1970, 0.2290, 0.1644, 0.2303, 0.0815])
Diff: 0.113998
tensor([0.0980, 0.1974, 0.2284, 0.1643, 0.2301, 0.0816])
Diff: 0.114347
tensor([0.0981, 0.1979, 0.2287, 0.1638, 0.2299, 0.0817])
Diff: 0.114715
tensor([0.0982, 0.1979, 0.2288, 0.1634, 0.2300, 0.0818])
Diff: 0.114745
tensor([0.0984, 0.1981, 0.2283, 0.1635, 0.2300, 0.0818])
Diff: 0

tensor([0.0990, 0.1997, 0.2208, 0.1728, 0.2269, 0.0808])
Diff: 0.108320
tensor([0.0989, 0.1998, 0.2207, 0.1731, 0.2267, 0.0807])
Diff: 0.107987
tensor([0.0990, 0.1996, 0.2201, 0.1737, 0.2268, 0.0807])
Diff: 0.108432
tensor([0.0990, 0.1995, 0.2211, 0.1727, 0.2268, 0.0808])
Diff: 0.107243
tensor([0.0991, 0.1985, 0.2209, 0.1740, 0.2267, 0.0808])
Diff: 0.108613
tensor([0.0994, 0.1994, 0.2195, 0.1735, 0.2273, 0.0810])
Diff: 0.109595
tensor([0.0994, 0.2000, 0.2191, 0.1728, 0.2277, 0.0810])
Diff: 0.109546
tensor([0.0992, 0.2001, 0.2187, 0.1732, 0.2279, 0.0808])
Diff: 0.109733
tensor([0.0992, 0.1997, 0.2185, 0.1733, 0.2285, 0.0808])
Diff: 0.110035
tensor([0.0993, 0.2000, 0.2186, 0.1729, 0.2283, 0.0808])
Diff: 0.109637
tensor([0.0994, 0.2004, 0.2184, 0.1732, 0.2277, 0.0809])
Diff: 0.109237
tensor([0.0995, 0.2000, 0.2186, 0.1734, 0.2275, 0.0809])
Diff: 0.109004
tensor([0.0997, 0.1994, 0.2177, 0.1743, 0.2280, 0.0809])
Diff: 0.109800
tensor([0.0998, 0.1991, 0.2179, 0.1735, 0.2287, 0.0811])
Diff: 0

Diff: 0.117246
tensor([0.0991, 0.2001, 0.2069, 0.1755, 0.2372, 0.0812])
Diff: 0.116287
tensor([0.0991, 0.2000, 0.2075, 0.1759, 0.2364, 0.0811])
Diff: 0.116948
tensor([0.0990, 0.2007, 0.2076, 0.1751, 0.2364, 0.0812])
Diff: 0.115815
tensor([0.0988, 0.2010, 0.2081, 0.1756, 0.2353, 0.0812])
Diff: 0.116172
tensor([0.0990, 0.2017, 0.2068, 0.1761, 0.2351, 0.0812])
Diff: 0.115615
tensor([0.0989, 0.2016, 0.2077, 0.1760, 0.2347, 0.0811])
Diff: 0.116414
tensor([0.0988, 0.2026, 0.2063, 0.1763, 0.2350, 0.0811])
Diff: 0.115572
tensor([0.0988, 0.2024, 0.2066, 0.1768, 0.2344, 0.0810])
Diff: 0.115618
tensor([0.0990, 0.2025, 0.2068, 0.1764, 0.2342, 0.0811])
Diff: 0.115266
tensor([0.0989, 0.2026, 0.2070, 0.1766, 0.2338, 0.0812])
Diff: 0.115288
tensor([0.0989, 0.2031, 0.2067, 0.1767, 0.2335, 0.0811])
Diff: 0.115650
tensor([0.0991, 0.2039, 0.2065, 0.1762, 0.2331, 0.0812])
Diff: 0.115585
tensor([0.0993, 0.2040, 0.2057, 0.1768, 0.2329, 0.0813])
Diff: 0.116187
tensor([0.0993, 0.2042, 0.2051, 0.1766, 0.2332, 0

Diff: 0.117008
tensor([0.0960, 0.2028, 0.2056, 0.1775, 0.2373, 0.0806])
Diff: 0.116433
tensor([0.0958, 0.2025, 0.2062, 0.1778, 0.2371, 0.0805])
Diff: 0.116725
tensor([0.0958, 0.2021, 0.2054, 0.1782, 0.2378, 0.0806])
Diff: 0.117144
tensor([0.0957, 0.2024, 0.2051, 0.1781, 0.2380, 0.0807])
Diff: 0.117205
tensor([0.0959, 0.2030, 0.2048, 0.1779, 0.2375, 0.0809])
Diff: 0.118259
tensor([0.0959, 0.2033, 0.2043, 0.1774, 0.2382, 0.0808])
Diff: 0.119212
tensor([0.0959, 0.2043, 0.2039, 0.1768, 0.2384, 0.0807])
Diff: 0.120000
tensor([0.0961, 0.2045, 0.2041, 0.1758, 0.2387, 0.0807])
Diff: 0.119823
tensor([0.0962, 0.2047, 0.2037, 0.1761, 0.2384, 0.0808])
Diff: 0.120097
tensor([0.0961, 0.2041, 0.2041, 0.1758, 0.2391, 0.0808])
Diff: 0.119591
tensor([0.0961, 0.2043, 0.2037, 0.1765, 0.2386, 0.0809])
Diff: 0.120277
tensor([0.0960, 0.2046, 0.2040, 0.1757, 0.2389, 0.0807])
Diff: 0.120616
tensor([0.0961, 0.2048, 0.2031, 0.1760, 0.2392, 0.0808])
Diff: 0.121161
tensor([0.0962, 0.2044, 0.2041, 0.1749, 0.2398, 0

Diff: 0.116818
tensor([0.0965, 0.1954, 0.2034, 0.1815, 0.2427, 0.0805])
Diff: 0.117991
tensor([0.0967, 0.1958, 0.2019, 0.1816, 0.2435, 0.0806])
Diff: 0.118158
tensor([0.0966, 0.1958, 0.2015, 0.1818, 0.2437, 0.0805])
Diff: 0.118674
tensor([0.0965, 0.1958, 0.2014, 0.1815, 0.2441, 0.0806])
Diff: 0.118283
tensor([0.0964, 0.1957, 0.2018, 0.1817, 0.2440, 0.0805])
Diff: 0.118723
tensor([0.0964, 0.1957, 0.2015, 0.1815, 0.2444, 0.0804])
Diff: 0.118577
tensor([0.0963, 0.1957, 0.2020, 0.1813, 0.2442, 0.0805])
Diff: 0.118724
tensor([0.0964, 0.1959, 0.2024, 0.1807, 0.2441, 0.0805])
Diff: 0.118174
tensor([0.0965, 0.1960, 0.2024, 0.1811, 0.2436, 0.0805])
Diff: 0.117579
tensor([0.0964, 0.1961, 0.2019, 0.1819, 0.2430, 0.0806])
Diff: 0.117206
tensor([0.0964, 0.1958, 0.2022, 0.1821, 0.2429, 0.0807])
Diff: 0.116272
tensor([0.0963, 0.1954, 0.2024, 0.1828, 0.2424, 0.0807])
Diff: 0.116288
tensor([0.0963, 0.1959, 0.2025, 0.1826, 0.2421, 0.0807])
Diff: 0.115935
tensor([0.0961, 0.1954, 0.2026, 0.1830, 0.2423, 0

tensor([0.0965, 0.2027, 0.2018, 0.1733, 0.2437, 0.0821])
Diff: 0.124392
tensor([0.0966, 0.2023, 0.2022, 0.1735, 0.2434, 0.0821])
Diff: 0.124843
tensor([0.0966, 0.2026, 0.2022, 0.1730, 0.2434, 0.0821])
Diff: 0.123590
tensor([0.0964, 0.2028, 0.2017, 0.1745, 0.2425, 0.0820])
Diff: 0.123664
tensor([0.0963, 0.2027, 0.2016, 0.1746, 0.2428, 0.0820])
Diff: 0.124268
tensor([0.0963, 0.2028, 0.2015, 0.1741, 0.2432, 0.0820])
Diff: 0.124055
tensor([0.0962, 0.2023, 0.2019, 0.1741, 0.2434, 0.0821])
Diff: 0.124335
tensor([0.0962, 0.2025, 0.2019, 0.1738, 0.2434, 0.0821])
Diff: 0.123424
tensor([0.0960, 0.2017, 0.2021, 0.1747, 0.2434, 0.0821])
Diff: 0.123733
tensor([0.0961, 0.2021, 0.2017, 0.1746, 0.2433, 0.0821])
Diff: 0.123831
tensor([0.0961, 0.2019, 0.2020, 0.1744, 0.2435, 0.0820])
Diff: 0.123607
tensor([0.0961, 0.2012, 0.2013, 0.1754, 0.2440, 0.0820])
Diff: 0.123600
tensor([0.0960, 0.2014, 0.2012, 0.1755, 0.2440, 0.0819])
Diff: 0.124679
tensor([0.0962, 0.2017, 0.2005, 0.1750, 0.2446, 0.0820])
Diff: 0

Diff: 0.133062
tensor([0.0971, 0.2103, 0.2063, 0.1612, 0.2429, 0.0821])
Diff: 0.132939
tensor([0.0972, 0.2102, 0.2066, 0.1610, 0.2428, 0.0822])
Diff: 0.132552
tensor([0.0973, 0.2107, 0.2068, 0.1611, 0.2419, 0.0823])
Diff: 0.132023
tensor([0.0971, 0.2116, 0.2072, 0.1612, 0.2409, 0.0821])
Diff: 0.132491
tensor([0.0972, 0.2117, 0.2069, 0.1609, 0.2410, 0.0822])
Diff: 0.133139
tensor([0.0971, 0.2121, 0.2060, 0.1610, 0.2416, 0.0821])
Diff: 0.132094
tensor([0.0970, 0.2122, 0.2061, 0.1619, 0.2408, 0.0821])
Diff: 0.132284
tensor([0.0972, 0.2119, 0.2057, 0.1619, 0.2411, 0.0822])
Diff: 0.132675
tensor([0.0972, 0.2113, 0.2056, 0.1618, 0.2419, 0.0823])
Diff: 0.133585
tensor([0.0972, 0.2115, 0.2050, 0.1614, 0.2426, 0.0823])
Diff: 0.132923
tensor([0.0974, 0.2110, 0.2049, 0.1620, 0.2423, 0.0824])
Diff: 0.133083
tensor([0.0974, 0.2107, 0.2046, 0.1621, 0.2427, 0.0825])
Diff: 0.133477
tensor([0.0974, 0.2109, 0.2042, 0.1620, 0.2429, 0.0826])
Diff: 0.133114
tensor([0.0973, 0.2107, 0.2040, 0.1625, 0.2429, 0

Diff: 0.126475
tensor([0.0980, 0.2024, 0.2138, 0.1623, 0.2408, 0.0826])
Diff: 0.126167
tensor([0.0980, 0.2024, 0.2139, 0.1625, 0.2406, 0.0827])
Diff: 0.125858
tensor([0.0980, 0.2022, 0.2137, 0.1629, 0.2405, 0.0827])
Diff: 0.126833
tensor([0.0981, 0.2020, 0.2129, 0.1627, 0.2417, 0.0827])
Diff: 0.126663
tensor([0.0982, 0.2016, 0.2129, 0.1629, 0.2417, 0.0827])
Diff: 0.126443
tensor([0.0981, 0.2026, 0.2137, 0.1623, 0.2407, 0.0827])
Diff: 0.125191
tensor([0.0980, 0.2021, 0.2145, 0.1629, 0.2399, 0.0826])
Diff: 0.125299
tensor([0.0982, 0.2025, 0.2132, 0.1635, 0.2399, 0.0827])
Diff: 0.125647
tensor([0.0983, 0.2016, 0.2129, 0.1637, 0.2410, 0.0827])
Diff: 0.125944
tensor([0.0984, 0.2018, 0.2128, 0.1634, 0.2410, 0.0826])
Diff: 0.127030
tensor([0.0982, 0.2027, 0.2124, 0.1627, 0.2413, 0.0827])
Diff: 0.126386
tensor([0.0982, 0.2020, 0.2127, 0.1632, 0.2413, 0.0827])
Diff: 0.126473
tensor([0.0982, 0.2025, 0.2121, 0.1634, 0.2412, 0.0826])
Diff: 0.126069
tensor([0.0982, 0.2020, 0.2122, 0.1637, 0.2411, 0

tensor([0.0989, 0.2003, 0.2144, 0.1597, 0.2429, 0.0837])
Diff: 0.128908
tensor([0.0990, 0.2003, 0.2142, 0.1598, 0.2429, 0.0837])
Diff: 0.128859
tensor([0.0989, 0.2006, 0.2147, 0.1595, 0.2426, 0.0837])
Diff: 0.129107
tensor([0.0988, 0.2003, 0.2149, 0.1592, 0.2430, 0.0838])
Diff: 0.129240
tensor([0.0989, 0.1996, 0.2155, 0.1589, 0.2434, 0.0838])
Diff: 0.129977
tensor([0.0990, 0.2003, 0.2146, 0.1587, 0.2436, 0.0838])
Diff: 0.130210
tensor([0.0990, 0.2001, 0.2149, 0.1582, 0.2437, 0.0841])
Diff: 0.129770
tensor([0.0990, 0.1996, 0.2155, 0.1583, 0.2436, 0.0840])
Diff: 0.129635
tensor([0.0989, 0.1991, 0.2150, 0.1590, 0.2441, 0.0839])
Diff: 0.130039
tensor([0.0988, 0.1986, 0.2144, 0.1593, 0.2451, 0.0839])
Diff: 0.129872
tensor([0.0987, 0.1985, 0.2140, 0.1597, 0.2452, 0.0838])
Diff: 0.129544
tensor([0.0986, 0.1991, 0.2155, 0.1589, 0.2442, 0.0837])
Diff: 0.131010
tensor([0.0986, 0.2000, 0.2148, 0.1580, 0.2449, 0.0836])
Diff: 0.131043
tensor([0.0986, 0.1994, 0.2158, 0.1575, 0.2450, 0.0836])
Diff: 0

Diff: 0.137650
tensor([0.1001, 0.2024, 0.2125, 0.1527, 0.2474, 0.0848])
Diff: 0.138271
tensor([0.1002, 0.2025, 0.2124, 0.1523, 0.2478, 0.0849])
Diff: 0.137558
tensor([0.1004, 0.2028, 0.2132, 0.1521, 0.2466, 0.0850])
Diff: 0.136838
tensor([0.1003, 0.2037, 0.2129, 0.1527, 0.2456, 0.0848])
Diff: 0.135859
tensor([0.1001, 0.2036, 0.2137, 0.1531, 0.2448, 0.0847])
Diff: 0.136492
tensor([0.1000, 0.2039, 0.2129, 0.1530, 0.2453, 0.0848])
Diff: 0.136485
tensor([0.1002, 0.2041, 0.2121, 0.1535, 0.2453, 0.0849])
Diff: 0.136754
tensor([0.1002, 0.2040, 0.2121, 0.1533, 0.2456, 0.0848])
Diff: 0.136153
tensor([0.1002, 0.2035, 0.2131, 0.1532, 0.2452, 0.0848])
Diff: 0.135570
tensor([0.1003, 0.2037, 0.2128, 0.1537, 0.2446, 0.0848])
Diff: 0.135350
tensor([0.1002, 0.2030, 0.2136, 0.1537, 0.2449, 0.0846])
Diff: 0.134745
tensor([0.1002, 0.2034, 0.2137, 0.1540, 0.2441, 0.0846])
Diff: 0.134871
tensor([0.1001, 0.2037, 0.2134, 0.1541, 0.2442, 0.0845])
Diff: 0.134493
tensor([0.0999, 0.2035, 0.2144, 0.1540, 0.2439, 0

tensor([0.0992, 0.2037, 0.2136, 0.1533, 0.2468, 0.0835])
Diff: 0.136824
tensor([0.0991, 0.2037, 0.2142, 0.1530, 0.2468, 0.0833])
Diff: 0.136751
tensor([0.0991, 0.2042, 0.2141, 0.1530, 0.2463, 0.0833])
Diff: 0.137182
tensor([0.0994, 0.2037, 0.2130, 0.1533, 0.2472, 0.0835])
Diff: 0.136324
tensor([0.0993, 0.2033, 0.2133, 0.1539, 0.2467, 0.0836])
Diff: 0.135757
tensor([0.0993, 0.2037, 0.2135, 0.1540, 0.2458, 0.0836])
Diff: 0.135472
tensor([0.0993, 0.2041, 0.2126, 0.1548, 0.2456, 0.0837])
Diff: 0.134145
tensor([0.0992, 0.2038, 0.2130, 0.1557, 0.2447, 0.0836])
Diff: 0.133120
tensor([0.0991, 0.2031, 0.2140, 0.1560, 0.2442, 0.0836])
Diff: 0.132794
tensor([0.0991, 0.2027, 0.2152, 0.1555, 0.2438, 0.0836])
Diff: 0.132489
tensor([0.0992, 0.2025, 0.2150, 0.1560, 0.2438, 0.0836])
Diff: 0.132408
tensor([0.0991, 0.2029, 0.2153, 0.1557, 0.2433, 0.0836])
Diff: 0.132099
tensor([0.0991, 0.2030, 0.2165, 0.1551, 0.2426, 0.0837])
Diff: 0.131651
tensor([0.0990, 0.2031, 0.2169, 0.1552, 0.2420, 0.0837])
Diff: 0

tensor([0.0988, 0.2092, 0.2261, 0.1525, 0.2326, 0.0808])
Diff: 0.127916
tensor([0.0988, 0.2086, 0.2270, 0.1525, 0.2324, 0.0808])
Diff: 0.127844
tensor([0.0986, 0.2075, 0.2284, 0.1520, 0.2328, 0.0807])
Diff: 0.127499
tensor([0.0984, 0.2074, 0.2293, 0.1520, 0.2324, 0.0806])
Diff: 0.127735
tensor([0.0983, 0.2071, 0.2300, 0.1515, 0.2326, 0.0805])
Diff: 0.128525
tensor([0.0982, 0.2073, 0.2298, 0.1510, 0.2332, 0.0805])
Diff: 0.129717
tensor([0.0985, 0.2074, 0.2293, 0.1501, 0.2340, 0.0807])
Diff: 0.130693
tensor([0.0983, 0.2070, 0.2294, 0.1495, 0.2352, 0.0807])
Diff: 0.131220
tensor([0.0984, 0.2067, 0.2302, 0.1486, 0.2353, 0.0807])
Diff: 0.131788
tensor([0.0984, 0.2065, 0.2310, 0.1478, 0.2356, 0.0807])
Diff: 0.131407
tensor([0.0983, 0.2065, 0.2302, 0.1486, 0.2358, 0.0806])
Diff: 0.131077
tensor([0.0981, 0.2064, 0.2299, 0.1490, 0.2358, 0.0807])
Diff: 0.130964
tensor([0.0981, 0.2062, 0.2294, 0.1494, 0.2362, 0.0807])
Diff: 0.130597
tensor([0.0981, 0.2062, 0.2296, 0.1497, 0.2359, 0.0806])
Diff: 0

tensor([0.0989, 0.2075, 0.2218, 0.1473, 0.2426, 0.0819])
Diff: 0.137724
tensor([0.0990, 0.2080, 0.2221, 0.1472, 0.2419, 0.0819])
Diff: 0.138392
tensor([0.0990, 0.2084, 0.2218, 0.1467, 0.2421, 0.0819])
Diff: 0.137920
tensor([0.0991, 0.2081, 0.2220, 0.1470, 0.2419, 0.0819])
Diff: 0.137905
tensor([0.0992, 0.2080, 0.2212, 0.1473, 0.2421, 0.0821])
Diff: 0.137725
tensor([0.0990, 0.2081, 0.2217, 0.1473, 0.2419, 0.0821])
Diff: 0.137715
tensor([0.0991, 0.2072, 0.2221, 0.1472, 0.2423, 0.0821])
Diff: 0.138150
tensor([0.0990, 0.2073, 0.2218, 0.1471, 0.2428, 0.0820])
Diff: 0.137391
tensor([0.0991, 0.2067, 0.2225, 0.1474, 0.2423, 0.0820])
Diff: 0.136275
tensor([0.0991, 0.2066, 0.2220, 0.1485, 0.2418, 0.0819])
Diff: 0.136191
tensor([0.0992, 0.2065, 0.2216, 0.1489, 0.2420, 0.0819])
Diff: 0.135237
tensor([0.0990, 0.2061, 0.2221, 0.1495, 0.2415, 0.0818])
Diff: 0.135971
tensor([0.0989, 0.2057, 0.2213, 0.1495, 0.2428, 0.0819])
Diff: 0.136253
tensor([0.0991, 0.2062, 0.2199, 0.1498, 0.2429, 0.0820])
Diff: 0

tensor([0.0977, 0.1999, 0.2343, 0.1400, 0.2474, 0.0806])
Diff: 0.141576
tensor([0.0977, 0.1995, 0.2345, 0.1404, 0.2473, 0.0805])
Diff: 0.141889
tensor([0.0979, 0.1989, 0.2343, 0.1403, 0.2479, 0.0807])
Diff: 0.141688
tensor([0.0979, 0.1990, 0.2351, 0.1400, 0.2472, 0.0807])
Diff: 0.141300
tensor([0.0979, 0.1993, 0.2338, 0.1409, 0.2473, 0.0808])
Diff: 0.141333
tensor([0.0980, 0.1998, 0.2333, 0.1409, 0.2471, 0.0808])
Diff: 0.142334
tensor([0.0980, 0.1998, 0.2325, 0.1405, 0.2482, 0.0809])
Diff: 0.141906
tensor([0.0979, 0.1996, 0.2330, 0.1408, 0.2480, 0.0808])
Diff: 0.141535
tensor([0.0978, 0.1992, 0.2327, 0.1413, 0.2482, 0.0807])
Diff: 0.140256
tensor([0.0978, 0.1993, 0.2328, 0.1422, 0.2471, 0.0808])
Diff: 0.139558
tensor([0.0979, 0.1999, 0.2326, 0.1426, 0.2461, 0.0809])
Diff: 0.139838
tensor([0.0979, 0.1999, 0.2318, 0.1428, 0.2467, 0.0809])
Diff: 0.139878
tensor([0.0980, 0.1999, 0.2329, 0.1421, 0.2461, 0.0809])
Diff: 0.140348
tensor([0.0981, 0.1997, 0.2321, 0.1423, 0.2470, 0.0809])
Diff: 0

tensor([0.0971, 0.1984, 0.2399, 0.1423, 0.2418, 0.0805])
Diff: 0.135626
tensor([0.0971, 0.1983, 0.2399, 0.1428, 0.2415, 0.0804])
Diff: 0.134970
tensor([0.0971, 0.1984, 0.2404, 0.1430, 0.2407, 0.0804])
Diff: 0.135919
tensor([0.0969, 0.1987, 0.2413, 0.1420, 0.2409, 0.0803])
Diff: 0.135112
tensor([0.0967, 0.1987, 0.2426, 0.1421, 0.2398, 0.0802])
Diff: 0.135163
tensor([0.0967, 0.1986, 0.2419, 0.1424, 0.2402, 0.0802])
Diff: 0.134814
tensor([0.0968, 0.1984, 0.2432, 0.1421, 0.2394, 0.0802])
Diff: 0.135090
tensor([0.0967, 0.1985, 0.2432, 0.1419, 0.2395, 0.0802])
Diff: 0.134193
tensor([0.0968, 0.1976, 0.2448, 0.1420, 0.2386, 0.0802])
Diff: 0.134579
tensor([0.0968, 0.1972, 0.2451, 0.1417, 0.2391, 0.0801])
Diff: 0.134335
tensor([0.0967, 0.1972, 0.2450, 0.1420, 0.2391, 0.0801])
Diff: 0.133671
tensor([0.0967, 0.1972, 0.2447, 0.1426, 0.2386, 0.0802])
Diff: 0.133330
tensor([0.0966, 0.1978, 0.2450, 0.1425, 0.2377, 0.0803])
Diff: 0.133062
tensor([0.0966, 0.1977, 0.2451, 0.1427, 0.2376, 0.0803])
Diff: 0

tensor([0.0979, 0.1965, 0.2514, 0.1467, 0.2269, 0.0805])
Diff: 0.124520
tensor([0.0980, 0.1963, 0.2514, 0.1465, 0.2273, 0.0805])
Diff: 0.124382
tensor([0.0981, 0.1963, 0.2514, 0.1466, 0.2272, 0.0805])
Diff: 0.123892
tensor([0.0978, 0.1966, 0.2518, 0.1468, 0.2265, 0.0804])
Diff: 0.123604
tensor([0.0978, 0.1968, 0.2523, 0.1469, 0.2259, 0.0803])
Diff: 0.124016
tensor([0.0978, 0.1968, 0.2521, 0.1467, 0.2264, 0.0803])
Diff: 0.123810
tensor([0.0977, 0.1963, 0.2534, 0.1465, 0.2260, 0.0802])
Diff: 0.123686
tensor([0.0979, 0.1966, 0.2522, 0.1468, 0.2261, 0.0804])
Diff: 0.123327
tensor([0.0979, 0.1956, 0.2537, 0.1468, 0.2258, 0.0802])
Diff: 0.122440
tensor([0.0978, 0.1949, 0.2535, 0.1477, 0.2259, 0.0802])
Diff: 0.121977
tensor([0.0978, 0.1953, 0.2539, 0.1478, 0.2248, 0.0802])
Diff: 0.121642
tensor([0.0976, 0.1949, 0.2536, 0.1484, 0.2254, 0.0801])
Diff: 0.120659
tensor([0.0974, 0.1944, 0.2549, 0.1489, 0.2244, 0.0800])
Diff: 0.120876
tensor([0.0973, 0.1940, 0.2551, 0.1488, 0.2248, 0.0799])
Diff: 0

Diff: 0.122730
tensor([0.0992, 0.1887, 0.2714, 0.1430, 0.2159, 0.0818])
Diff: 0.122171
tensor([0.0991, 0.1879, 0.2726, 0.1434, 0.2152, 0.0817])
Diff: 0.122242
tensor([0.0990, 0.1875, 0.2725, 0.1435, 0.2159, 0.0816])
Diff: 0.121914
tensor([0.0989, 0.1879, 0.2730, 0.1437, 0.2150, 0.0815])
Diff: 0.122299
tensor([0.0986, 0.1872, 0.2744, 0.1434, 0.2150, 0.0813])
Diff: 0.121466
tensor([0.0986, 0.1876, 0.2732, 0.1442, 0.2151, 0.0814])
Diff: 0.120655
tensor([0.0985, 0.1875, 0.2728, 0.1449, 0.2148, 0.0815])
Diff: 0.120602
tensor([0.0985, 0.1879, 0.2728, 0.1448, 0.2144, 0.0815])
Diff: 0.120408
tensor([0.0984, 0.1869, 0.2740, 0.1450, 0.2142, 0.0815])
Diff: 0.120577
tensor([0.0985, 0.1867, 0.2728, 0.1450, 0.2153, 0.0816])
Diff: 0.121080
tensor([0.0985, 0.1862, 0.2735, 0.1446, 0.2155, 0.0816])
Diff: 0.119814
tensor([0.0986, 0.1861, 0.2721, 0.1459, 0.2158, 0.0816])
Diff: 0.119725
tensor([0.0984, 0.1853, 0.2731, 0.1460, 0.2156, 0.0816])
Diff: 0.120167
tensor([0.0983, 0.1858, 0.2729, 0.1456, 0.2159, 0

Diff: 0.129977
tensor([0.0967, 0.1920, 0.2701, 0.1377, 0.2219, 0.0816])
Diff: 0.129945
tensor([0.0969, 0.1913, 0.2697, 0.1379, 0.2226, 0.0816])
Diff: 0.130203
tensor([0.0970, 0.1918, 0.2684, 0.1378, 0.2233, 0.0817])
Diff: 0.129865
tensor([0.0970, 0.1912, 0.2693, 0.1380, 0.2227, 0.0817])
Diff: 0.129467
tensor([0.0970, 0.1906, 0.2694, 0.1384, 0.2229, 0.0818])
Diff: 0.129477
tensor([0.0969, 0.1907, 0.2696, 0.1383, 0.2226, 0.0818])
Diff: 0.129538
tensor([0.0969, 0.1909, 0.2693, 0.1383, 0.2228, 0.0818])
Diff: 0.128900
tensor([0.0970, 0.1912, 0.2683, 0.1389, 0.2228, 0.0819])
Diff: 0.129268
tensor([0.0967, 0.1909, 0.2692, 0.1386, 0.2228, 0.0818])
Diff: 0.129253
tensor([0.0966, 0.1900, 0.2705, 0.1385, 0.2226, 0.0819])
Diff: 0.129705
tensor([0.0967, 0.1902, 0.2695, 0.1382, 0.2234, 0.0820])
Diff: 0.128997
tensor([0.0966, 0.1908, 0.2679, 0.1390, 0.2237, 0.0821])
Diff: 0.128045
tensor([0.0967, 0.1905, 0.2666, 0.1400, 0.2240, 0.0822])
Diff: 0.128658
tensor([0.0967, 0.1905, 0.2657, 0.1398, 0.2250, 0

Diff: 0.133399
tensor([0.0972, 0.1863, 0.2742, 0.1350, 0.2250, 0.0824])
Diff: 0.134008
tensor([0.0972, 0.1868, 0.2735, 0.1345, 0.2256, 0.0824])
Diff: 0.134685
tensor([0.0973, 0.1870, 0.2746, 0.1337, 0.2250, 0.0823])
Diff: 0.133615
tensor([0.0973, 0.1877, 0.2736, 0.1346, 0.2245, 0.0824])
Diff: 0.133664
tensor([0.0973, 0.1876, 0.2742, 0.1345, 0.2241, 0.0824])
Diff: 0.133592
tensor([0.0974, 0.1880, 0.2733, 0.1345, 0.2243, 0.0824])
Diff: 0.133014
tensor([0.0973, 0.1885, 0.2735, 0.1349, 0.2234, 0.0823])
Diff: 0.132734
tensor([0.0973, 0.1889, 0.2736, 0.1350, 0.2228, 0.0823])
Diff: 0.133082
tensor([0.0974, 0.1896, 0.2720, 0.1349, 0.2238, 0.0823])
Diff: 0.132930
tensor([0.0973, 0.1893, 0.2727, 0.1350, 0.2235, 0.0822])
Diff: 0.132578
tensor([0.0974, 0.1900, 0.2712, 0.1354, 0.2237, 0.0824])
Diff: 0.132813
tensor([0.0974, 0.1898, 0.2715, 0.1351, 0.2237, 0.0825])
Diff: 0.132663
tensor([0.0971, 0.1901, 0.2718, 0.1352, 0.2233, 0.0824])
Diff: 0.132591
tensor([0.0972, 0.1894, 0.2719, 0.1354, 0.2237, 0

tensor([0.0962, 0.1987, 0.2725, 0.1265, 0.2242, 0.0820])
Diff: 0.142832
tensor([0.0962, 0.1989, 0.2730, 0.1260, 0.2240, 0.0819])
Diff: 0.143337
tensor([0.0963, 0.1986, 0.2732, 0.1255, 0.2244, 0.0821])
Diff: 0.143478
tensor([0.0962, 0.1982, 0.2743, 0.1253, 0.2241, 0.0819])
Diff: 0.143295
tensor([0.0962, 0.1985, 0.2734, 0.1256, 0.2244, 0.0818])
Diff: 0.143358
tensor([0.0962, 0.1996, 0.2730, 0.1255, 0.2239, 0.0818])
Diff: 0.143365
tensor([0.0962, 0.1991, 0.2735, 0.1256, 0.2241, 0.0816])
Diff: 0.143344
tensor([0.0963, 0.1994, 0.2730, 0.1256, 0.2240, 0.0817])
Diff: 0.143025
tensor([0.0963, 0.1989, 0.2736, 0.1258, 0.2238, 0.0816])
Diff: 0.142327
tensor([0.0964, 0.1988, 0.2735, 0.1263, 0.2232, 0.0819])
Diff: 0.142817
tensor([0.0963, 0.1992, 0.2731, 0.1259, 0.2236, 0.0819])
Diff: 0.143455
tensor([0.0960, 0.1984, 0.2750, 0.1253, 0.2235, 0.0818])
Diff: 0.143228
tensor([0.0959, 0.1980, 0.2743, 0.1257, 0.2243, 0.0819])
Diff: 0.143640
tensor([0.0958, 0.1984, 0.2751, 0.1252, 0.2238, 0.0817])
Diff: 0

Diff: 0.143827
tensor([0.0966, 0.2003, 0.2690, 0.1257, 0.2265, 0.0820])
Diff: 0.143751
tensor([0.0962, 0.2004, 0.2694, 0.1259, 0.2264, 0.0817])
Diff: 0.143606
tensor([0.0962, 0.2003, 0.2694, 0.1260, 0.2264, 0.0818])
Diff: 0.143230
tensor([0.0961, 0.2008, 0.2698, 0.1262, 0.2255, 0.0816])
Diff: 0.143611
tensor([0.0959, 0.2006, 0.2711, 0.1257, 0.2250, 0.0816])
Diff: 0.143697
tensor([0.0960, 0.2012, 0.2712, 0.1255, 0.2245, 0.0816])
Diff: 0.142401
tensor([0.0960, 0.2013, 0.2709, 0.1266, 0.2236, 0.0816])
Diff: 0.142376
tensor([0.0961, 0.2021, 0.2694, 0.1268, 0.2241, 0.0816])
Diff: 0.142023
tensor([0.0961, 0.2017, 0.2690, 0.1272, 0.2243, 0.0817])
Diff: 0.141985
tensor([0.0961, 0.2018, 0.2683, 0.1274, 0.2249, 0.0816])
Diff: 0.142749
tensor([0.0960, 0.2012, 0.2694, 0.1266, 0.2251, 0.0817])
Diff: 0.142092
tensor([0.0959, 0.2010, 0.2695, 0.1271, 0.2247, 0.0818])
Diff: 0.140943
tensor([0.0961, 0.2001, 0.2695, 0.1281, 0.2244, 0.0818])
Diff: 0.140765
tensor([0.0962, 0.1992, 0.2702, 0.1282, 0.2244, 0

tensor([0.0968, 0.2016, 0.2631, 0.1283, 0.2281, 0.0821])
Diff: 0.142075
tensor([0.0968, 0.2013, 0.2640, 0.1281, 0.2278, 0.0821])
Diff: 0.141858
tensor([0.0968, 0.2014, 0.2634, 0.1283, 0.2279, 0.0821])
Diff: 0.141727
tensor([0.0968, 0.2014, 0.2624, 0.1287, 0.2285, 0.0822])
Diff: 0.141880
tensor([0.0968, 0.2012, 0.2622, 0.1286, 0.2289, 0.0822])
Diff: 0.142261
tensor([0.0966, 0.2018, 0.2633, 0.1281, 0.2282, 0.0821])
Diff: 0.142067
tensor([0.0966, 0.2009, 0.2626, 0.1285, 0.2292, 0.0821])
Diff: 0.142229
tensor([0.0966, 0.2008, 0.2622, 0.1285, 0.2298, 0.0822])
Diff: 0.143143
tensor([0.0964, 0.1998, 0.2635, 0.1277, 0.2305, 0.0821])
Diff: 0.143018
tensor([0.0966, 0.2004, 0.2630, 0.1277, 0.2301, 0.0823])
Diff: 0.143014
tensor([0.0966, 0.2002, 0.2629, 0.1277, 0.2302, 0.0823])
Diff: 0.142670
tensor([0.0966, 0.1995, 0.2640, 0.1278, 0.2297, 0.0823])
