In [27]:
import torch

torch.manual_seed(1)
X = torch.Tensor([[-1, 1, 10],[1, 1, 1]])
y = torch.Tensor([-1, 1, 1])
w = torch.Tensor([[0.1],[0.1]])
alpha = 1
print(X)
print(y)
print(w)
for iter in range(100):
    tmp = torch.exp(torch.matmul(torch.transpose(w,0,1),X)*(-y))

    ##############################
    ## Use tmp to compute f and g. Instead of summing we average the result, i.e.,
    ## complete only inside torch.mean(...) and don't remove this function
    ## Dimensions: f (scalar); g (2)
    ##############################
    f = torch.mean(torch.log(1+tmp))
    g = torch.mean((-y)*tmp/(1+tmp)*X,1)

    print("Loss: %f; ||g||: %f" % (f, torch.norm(g)))
    g = g.view(-1,1)
    w = w - alpha*g

print(w)

tensor([[-1.,  1., 10.],
        [ 1.,  1.,  1.]])
tensor([-1.,  1.,  1.])
tensor([[0.1000],
        [0.1000]])
Loss: 0.526207; ||g||: 1.151119
Loss: 0.169677; ||g||: 0.150690
Loss: 0.148274; ||g||: 0.133631
Loss: 0.131357; ||g||: 0.119766
Loss: 0.117707; ||g||: 0.108330
Loss: 0.106496; ||g||: 0.098769
Loss: 0.097145; ||g||: 0.090677
Loss: 0.089240; ||g||: 0.083753
Loss: 0.082479; ||g||: 0.077769
Loss: 0.076636; ||g||: 0.072552
Loss: 0.071540; ||g||: 0.067967
Loss: 0.067060; ||g||: 0.063909
Loss: 0.063092; ||g||: 0.060294
Loss: 0.059555; ||g||: 0.057055
Loss: 0.056384; ||g||: 0.054136
Loss: 0.053525; ||g||: 0.051495
Loss: 0.050936; ||g||: 0.049093
Loss: 0.048580; ||g||: 0.046900
Loss: 0.046428; ||g||: 0.044890
Loss: 0.044454; ||g||: 0.043042
Loss: 0.042638; ||g||: 0.041337
Loss: 0.040962; ||g||: 0.039760
Loss: 0.039411; ||g||: 0.038296
Loss: 0.037971; ||g||: 0.036934
Loss: 0.036630; ||g||: 0.035664
Loss: 0.035379; ||g||: 0.034477
Loss: 0.034210; ||g||: 0.033365
Loss: 0.033114; ||g||: 0

In [26]:
import torch
import torch.optim as optim

torch.manual_seed(1)
X = torch.Tensor([[-1, 1, 2],[1, 1, 1]])
y = torch.Tensor([-1, 1, 1])
w = torch.Tensor([[0.1],[0.1]])
w.requires_grad = True
alpha = 1
#lr: learning rate
optimizer = optim.SGD([w], lr=alpha)
optimizer.zero_grad()

for iter in range(100):
    tmp = torch.exp(torch.matmul(torch.transpose(w,0,1),X)*(-y))

    ##############################
    ## loss is the same as f in A2_LogisticRegression.py
    ## Dimensions: loss (scalar)
    ##############################
    loss = torch.mean(torch.log(1+tmp))

    loss.backward()
    print("Loss: %f; ||g||: %f" % (loss, torch.norm(w.grad)))

    ##############################
    ## Use two functions within the optimizer instance to perform the update step
    ##############################
    optimizer.step()
    optimizer.zero_grad()

print(w)


Loss: 0.615214; ||g||: 0.613350
Loss: 0.332295; ||g||: 0.332677
Loss: 0.238526; ||g||: 0.237049
Loss: 0.188502; ||g||: 0.187143
Loss: 0.156530; ||g||: 0.155550
Loss: 0.134098; ||g||: 0.133439
Loss: 0.117414; ||g||: 0.116985
Loss: 0.104489; ||g||: 0.104218
Loss: 0.094169; ||g||: 0.094005
Loss: 0.085731; ||g||: 0.085640
Loss: 0.078700; ||g||: 0.078658
Loss: 0.072749; ||g||: 0.072740
Loss: 0.067645; ||g||: 0.067658
Loss: 0.063218; ||g||: 0.063246
Loss: 0.059342; ||g||: 0.059380
Loss: 0.055918; ||g||: 0.055962
Loss: 0.052872; ||g||: 0.052920
Loss: 0.050145; ||g||: 0.050194
Loss: 0.047687; ||g||: 0.047738
Loss: 0.045462; ||g||: 0.045512
Loss: 0.043437; ||g||: 0.043487
Loss: 0.041586; ||g||: 0.041635
Loss: 0.039889; ||g||: 0.039936
Loss: 0.038325; ||g||: 0.038371
Loss: 0.036881; ||g||: 0.036925
Loss: 0.035542; ||g||: 0.035584
Loss: 0.034298; ||g||: 0.034339
Loss: 0.033139; ||g||: 0.033178
Loss: 0.032056; ||g||: 0.032094
Loss: 0.031043; ||g||: 0.031078
Loss: 0.030092; ||g||: 0.030126
Loss: 0.

In [ ]:
torch.manual_seed(1)
X = torch.Tensor([[-1, 1, 2],[1, 1, 1]])
y = torch.Tensor([-1,1,1])
w = torch.Tensor([[0.1],[0.1]])
w.requires_grad = True
alpha = 1
#lr: learning rate
optimizer = optim.SGD([w], lr=alpha)
optimizer.zero_grad()

tmp = torch.exp(torch.matmul(torch.transpose(w,0,1),X)*(-y))

    ##############################
    ## loss is the same as f in A2_LogisticRegression.py
    ## Dimensions: loss (scalar)
    ##############################
loss = torch.mean(torch.log(1+tmp))
print(loss)
loss.backward()

In [32]:
torch.empty(3).random_(2)

tensor([0., 0., 1.])

In [34]:
import torch
import torch.optim as optim
import torch.nn as nn

torch.manual_seed(1)
X = torch.Tensor([[-1, 1, 2],[1, 1, 1]])
##############################
## modify the dataset so that it can be used here and is equivalent to the one 
## used in A2_LogisticRegression2.py and A2_LogisticRegression.py
## Dimensions: y (3)
##############################
y = torch.Tensor([0,1,1])

alpha = 1

class ShallowNet(nn.Module):
    def __init__(self):
        super(ShallowNet, self).__init__()
        self.fc1 = nn.Linear(2,1, bias=False)
    
    def forward(self, X):
        return self.fc1(X)

net = ShallowNet()
print(net)

ShallowNet(
  (fc1): Linear(in_features=2, out_features=1, bias=False)
)


In [35]:
net.fc1.weight.data = torch.Tensor([[0.1, 0.1]])

print(net(torch.transpose(X,0,1)).squeeze())
print(net(torch.transpose(X,0,1)).squeeze().shape)

tensor([0.0000, 0.2000, 0.3000], grad_fn=<SqueezeBackward0>)
torch.Size([3])


In [36]:
optimizer = optim.SGD(net.parameters(), lr=alpha)
optimizer.zero_grad()

criterion = nn.BCEWithLogitsLoss()

for iter in range(100):
    netOutput = net(torch.transpose(X,0,1)).squeeze()

    ##############################
    ## provide the arguments for the criterion function
    ##############################
    loss = criterion(netOutput, y)
    
    loss.backward()
    gn = 0
    for f in net.parameters():
        gn = gn + torch.norm(f.grad)
    print("Loss: %f; ||g||: %f" % (loss, gn))
    optimizer.step()
    optimizer.zero_grad()

for f in net.parameters():
    print(f)

Loss: 0.615214; ||g||: 0.613350
Loss: 0.332295; ||g||: 0.332677
Loss: 0.238526; ||g||: 0.237049
Loss: 0.188502; ||g||: 0.187143
Loss: 0.156530; ||g||: 0.155550
Loss: 0.134098; ||g||: 0.133439
Loss: 0.117414; ||g||: 0.116985
Loss: 0.104489; ||g||: 0.104218
Loss: 0.094169; ||g||: 0.094005
Loss: 0.085731; ||g||: 0.085640
Loss: 0.078700; ||g||: 0.078658
Loss: 0.072749; ||g||: 0.072740
Loss: 0.067645; ||g||: 0.067658
Loss: 0.063218; ||g||: 0.063246
Loss: 0.059342; ||g||: 0.059380
Loss: 0.055918; ||g||: 0.055962
Loss: 0.052872; ||g||: 0.052920
Loss: 0.050144; ||g||: 0.050194
Loss: 0.047687; ||g||: 0.047738
Loss: 0.045462; ||g||: 0.045512
Loss: 0.043437; ||g||: 0.043487
Loss: 0.041586; ||g||: 0.041635
Loss: 0.039889; ||g||: 0.039936
Loss: 0.038325; ||g||: 0.038371
Loss: 0.036881; ||g||: 0.036925
Loss: 0.035542; ||g||: 0.035584
Loss: 0.034298; ||g||: 0.034339
Loss: 0.033139; ||g||: 0.033178
Loss: 0.032056; ||g||: 0.032094
Loss: 0.031043; ||g||: 0.031078
Loss: 0.030092; ||g||: 0.030126
Loss: 0.

In [8]:
a=torch.tensor([[1.,2.],[4.,5.]])
print(a)
torch.mean(a,1
           

tensor([[1., 2.],
        [4., 5.]])


tensor([1.5000, 4.5000])

In [11]:
a =torch.tensor([1.,2.,3])
X

tensor([[-1.,  1., 10.],
        [ 1.,  1.,  1.]])

In [12]:
a*X

tensor([[-1.,  2., 30.],
        [ 1.,  2.,  3.]])

In [13]:
torch.mul(a,X)

tensor([[-1.,  2., 30.],
        [ 1.,  2.,  3.]])