In [5]:
import torch
x = torch.DoubleTensor([[1],[2]])
y = torch.DoubleTensor([[1],[1]])
print(x.size())

torch.Size([2, 1])


In [6]:
X = torch.cat((x, torch.ones_like(x)),1)
print(X)
print(X[1,0])
# torch.matmul: matrix multiplication
print(torch.matmul(X,y))

tensor([[1., 1.],
        [2., 1.]], dtype=torch.float64)
tensor(2., dtype=torch.float64)
tensor([[2.],
        [3.]], dtype=torch.float64)


In [7]:
# Solution 1
##############################
## Fill in the arguments
##############################
res1 = torch.lstsq(y, X)
print("Solution 1:")
print(res1[0])


Solution 1:
tensor([[9.9301e-17],
        [1.0000e+00]], dtype=torch.float64)


In [11]:
print(torch.matmul(torch.transpose(X, 0, 1),X))
print(torch.matmul(torch.transpose(X, 0, 1),y))


tensor([[5., 3.],
        [3., 2.]], dtype=torch.float64)
tensor([[3.],
        [2.]], dtype=torch.float64)


In [12]:
##############################
## How to compute l and r?
## Dimensions: l (2x2); r (2x1)
##############################
l = torch.matmul(torch.transpose(X, 0, 1),X)
r = torch.matmul(torch.transpose(X, 0, 1),y)
res2 = torch.solve(r,l)
print("Solution 2:")
print(res2[0])

Solution 2:
tensor([[0.],
        [1.]], dtype=torch.float64)


In [14]:
# Solution 3
##############################
## What is l and r?
## Dimensions: l (2x2); r (2x1)
##############################
l = torch.matmul(torch.transpose(X, 0, 1),X)
r = torch.matmul(torch.transpose(X, 0, 1),y)
res3 = torch.matmul(torch.inverse(l),r)
print("Solution 3:")
print(res3)

Solution 3:
tensor([[0.],
        [1.]], dtype=torch.float64)


In [10]:
##############################
## Specify the matrix X
## Dimensions: X (3x3)
##############################
X = torch.Tensor([[0,0,1],[1,1,1],[4,2,1]])
y = torch.Tensor([[0],[1],[1]])
print(X)
print(y)

# Solution
##############################
## Use one of the ways to compute the result
##############################
l2 = torch.matmul(torch.transpose(X, 0, 1),X)
r2 = torch.matmul(torch.transpose(X, 0, 1),y)
res2 = torch.solve(r2,l2)

print(res2[0])

tensor([[0., 0., 1.],
        [1., 1., 1.],
        [4., 2., 1.]])
tensor([[0.],
        [1.],
        [1.]])
tensor([[-5.0000e-01],
        [ 1.5000e+00],
        [-2.9101e-07]])


In [11]:
res2 = torch.lstsq(r2,l2)
print(res2[0])

tensor([[-5.0000e-01],
        [ 1.5000e+00],
        [-1.6283e-07]])


In [13]:
-0.5*(1.5**2-1.5*3)

1.125

In [1]:
-5e-01

-0.5